/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-CommonDataTypes"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_PrivateIE_ID_H_
#define	_RANAP_PrivateIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_PrivateIE_ID_PR {
	RANAP_PrivateIE_ID_PR_NOTHING,	/* No components present */
	RANAP_PrivateIE_ID_PR_local,
	RANAP_PrivateIE_ID_PR_global
} RANAP_PrivateIE_ID_PR;

/* RANAP_PrivateIE-ID */
typedef struct RANAP_PrivateIE_ID {
	RANAP_PrivateIE_ID_PR present;
	union RANAP_PrivateIE_ID_u {
		long	 local;
		OBJECT_IDENTIFIER_t	 global;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_PrivateIE_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_PrivateIE_ID;
extern asn_CHOICE_specifics_t asn_SPC_RANAP_PrivateIE_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_PrivateIE_ID_1[2];
extern asn_per_constraints_t asn_PER_type_RANAP_PrivateIE_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_PrivateIE_ID_H_ */
#include <asn_internal.h>
