/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_RIMRoutingAddress_H_
#define	_RANAP_RIMRoutingAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_TargetRNC-ID.h>
#include <osmocom/ranap/RANAP_GERAN-Cell-ID.h>
#include <osmocom/ranap/RANAP_TargetENB-ID.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_RIMRoutingAddress_PR {
	RANAP_RIMRoutingAddress_PR_NOTHING,	/* No components present */
	RANAP_RIMRoutingAddress_PR_targetRNC_ID,
	RANAP_RIMRoutingAddress_PR_gERAN_Cell_ID,
	/* Extensions may appear below */
	RANAP_RIMRoutingAddress_PR_targeteNB_ID
} RANAP_RIMRoutingAddress_PR;

/* RANAP_RIMRoutingAddress */
typedef struct RANAP_RIMRoutingAddress {
	RANAP_RIMRoutingAddress_PR present;
	union RANAP_RIMRoutingAddress_u {
		RANAP_TargetRNC_ID_t	 targetRNC_ID;
		RANAP_GERAN_Cell_ID_t	 gERAN_Cell_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		RANAP_TargetENB_ID_t	 targeteNB_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_RIMRoutingAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_RIMRoutingAddress;
extern asn_CHOICE_specifics_t asn_SPC_RANAP_RIMRoutingAddress_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_RIMRoutingAddress_1[3];
extern asn_per_constraints_t asn_PER_type_RANAP_RIMRoutingAddress_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_RIMRoutingAddress_H_ */
#include <asn_internal.h>
