/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_PLMNs_in_shared_network_H_
#define	_RANAP_PLMNs_in_shared_network_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <osmocom/ranap/RANAP_PLMNidentity.h>
#include <osmocom/ranap/RANAP_LA-LIST.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct RANAP_PLMNs_in_shared_network__Member {
	RANAP_PLMNidentity_t	 pLMNidentity;
	RANAP_LA_LIST_t	 lA_LIST;
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PLMNs_in_shared_network__Member;

/* RANAP_PLMNs-in-shared-network */
typedef struct RANAP_PLMNs_in_shared_network {
	A_SEQUENCE_OF(PLMNs_in_shared_network__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_PLMNs_in_shared_network_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_PLMNs_in_shared_network;
extern asn_SET_OF_specifics_t asn_SPC_RANAP_PLMNs_in_shared_network_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_PLMNs_in_shared_network_1[1];
extern asn_per_constraints_t asn_PER_type_RANAP_PLMNs_in_shared_network_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_PLMNs_in_shared_network_H_ */
#include <asn_internal.h>
