/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_LoggingDuration_H_
#define	_RANAP_LoggingDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_LoggingDuration {
	RANAP_LoggingDuration_min10	= 0,
	RANAP_LoggingDuration_min20	= 1,
	RANAP_LoggingDuration_min40	= 2,
	RANAP_LoggingDuration_min60	= 3,
	RANAP_LoggingDuration_min90	= 4,
	RANAP_LoggingDuration_min120	= 5
	/*
	 * Enumeration is extensible
	 */
} e_RANAP_LoggingDuration;

/* RANAP_LoggingDuration */
typedef long	 RANAP_LoggingDuration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANAP_LoggingDuration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANAP_LoggingDuration;
extern const asn_INTEGER_specifics_t asn_SPC_LoggingDuration_specs_1;
asn_struct_free_f LoggingDuration_free;
asn_struct_print_f LoggingDuration_print;
asn_constr_check_f LoggingDuration_constraint;
ber_type_decoder_f LoggingDuration_decode_ber;
der_type_encoder_f LoggingDuration_encode_der;
xer_type_decoder_f LoggingDuration_decode_xer;
xer_type_encoder_f LoggingDuration_encode_xer;
oer_type_decoder_f LoggingDuration_decode_oer;
oer_type_encoder_f LoggingDuration_encode_oer;
per_type_decoder_f LoggingDuration_decode_uper;
per_type_encoder_f LoggingDuration_encode_uper;
per_type_decoder_f LoggingDuration_decode_aper;
per_type_encoder_f LoggingDuration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_LoggingDuration_H_ */
#include <asn_internal.h>
