/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_EncryptionInformation_H_
#define	_RANAP_EncryptionInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_PermittedEncryptionAlgorithms.h>
#include <osmocom/ranap/RANAP_EncryptionKey.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* RANAP_EncryptionInformation */
typedef struct RANAP_EncryptionInformation {
	RANAP_PermittedEncryptionAlgorithms_t	 permittedAlgorithms;
	RANAP_EncryptionKey_t	 key;
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_EncryptionInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_EncryptionInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_EncryptionInformation_H_ */
#include <asn_internal.h>
