/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_ImmediateMDT_H_
#define	_RANAP_ImmediateMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_MeasurementsToActivate.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_M1Report;
struct RANAP_M2Report;
struct RANAP_ProtocolExtensionContainer;

/* RANAP_ImmediateMDT */
typedef struct RANAP_ImmediateMDT {
	RANAP_MeasurementsToActivate_t	 measurementsToActivate;
	struct RANAP_M1Report	*m1report;	/* OPTIONAL */
	struct RANAP_M2Report	*m2report;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_ImmediateMDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_ImmediateMDT;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_ImmediateMDT_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_ImmediateMDT_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_ImmediateMDT_H_ */
#include <asn_internal.h>
