/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_DataVolumeList_H_
#define	_RANAP_DataVolumeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <osmocom/ranap/RANAP_UnsuccessfullyTransmittedDataVolume.h>
#include <osmocom/ranap/RANAP_DataVolumeReference.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct RANAP_DataVolumeList__Member {
	RANAP_UnsuccessfullyTransmittedDataVolume_t	 dl_UnsuccessfullyTransmittedDataVolume;
	RANAP_DataVolumeReference_t	*dataVolumeReference;	/* OPTIONAL */
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataVolumeList__Member;

/* RANAP_DataVolumeList */
typedef struct RANAP_DataVolumeList {
	A_SEQUENCE_OF(DataVolumeList__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_DataVolumeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_DataVolumeList;
extern asn_SET_OF_specifics_t asn_SPC_RANAP_DataVolumeList_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_DataVolumeList_1[1];
extern asn_per_constraints_t asn_PER_type_RANAP_DataVolumeList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_DataVolumeList_H_ */
#include <asn_internal.h>
