/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_HorizontalWithVerticalVelocityAndUncertainty_H_
#define	_RANAP_HorizontalWithVerticalVelocityAndUncertainty_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_HorizontalSpeedAndBearing.h>
#include <osmocom/ranap/RANAP_VerticalVelocity.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* RANAP_HorizontalWithVerticalVelocityAndUncertainty */
typedef struct RANAP_HorizontalWithVerticalVelocityAndUncertainty {
	RANAP_HorizontalSpeedAndBearing_t	 horizontalSpeedAndBearing;
	RANAP_VerticalVelocity_t	 veritcalVelocity;
	long	 horizontalUncertaintySpeed;
	long	 verticalUncertaintySpeed;
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_HorizontalWithVerticalVelocityAndUncertainty_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_HorizontalWithVerticalVelocityAndUncertainty;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_HorizontalWithVerticalVelocityAndUncertainty_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_HorizontalWithVerticalVelocityAndUncertainty_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_HorizontalWithVerticalVelocityAndUncertainty_H_ */
#include <asn_internal.h>
