/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-Containers"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_ProtocolIE_FieldPair_H_
#define	_RANAP_ProtocolIE_FieldPair_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_ProtocolIE-ID.h>
#include <osmocom/ranap/RANAP_Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <osmocom/ranap/RANAP_RAB-SetupOrModifyItemFirst.h>
#include <osmocom/ranap/RANAP_RAB-SetupOrModifyItemSecond.h>
#include <osmocom/ranap/RANAP_Presence.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_RAB_SetupOrModifyItem_IEs__firstValue_PR {
	RANAP_RAB_SetupOrModifyItem_IEs__firstValue_PR_NOTHING,	/* No components present */
	RANAP_RAB_SetupOrModifyItem_IEs__firstValue_PR_RAB_SetupOrModifyItemFirst
} RANAP_RAB_SetupOrModifyItem_IEs__firstValue_PR;
typedef enum RANAP_RAB_SetupOrModifyItem_IEs__secondValue_PR {
	RANAP_RAB_SetupOrModifyItem_IEs__secondValue_PR_NOTHING,	/* No components present */
	RANAP_RAB_SetupOrModifyItem_IEs__secondValue_PR_RAB_SetupOrModifyItemSecond
} RANAP_RAB_SetupOrModifyItem_IEs__secondValue_PR;

/* RANAP_ProtocolIE-FieldPair */
typedef struct RANAP_RAB_SetupOrModifyItem_IEs {
	RANAP_ProtocolIE_ID_t	 id;
	RANAP_Criticality_t	 firstCriticality;
	struct RANAP_RAB_SetupOrModifyItem_IEs__firstValue {
		RANAP_RAB_SetupOrModifyItem_IEs__firstValue_PR present;
		union RANAP_RAB_SetupOrModifyItem_IEs__RANAP_firstValue_u {
			RANAP_RAB_SetupOrModifyItemFirst_t	 RAB_SetupOrModifyItemFirst;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} firstValue;
	RANAP_Criticality_t	 secondCriticality;
	struct RANAP_RAB_SetupOrModifyItem_IEs__secondValue {
		RANAP_RAB_SetupOrModifyItem_IEs__secondValue_PR present;
		union RANAP_RAB_SetupOrModifyItem_IEs__RANAP_secondValue_u {
			RANAP_RAB_SetupOrModifyItemSecond_t	 RAB_SetupOrModifyItemSecond;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} secondValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_RAB_SetupOrModifyItem_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_RAB_SetupOrModifyItem_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_RAB_SetupOrModifyItem_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_RAB_SetupOrModifyItem_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_ProtocolIE_FieldPair_H_ */
#include <asn_internal.h>
