/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_RAB_SetupOrModifyItemFirst_H_
#define	_RANAP_RAB_SetupOrModifyItemFirst_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_RAB-ID.h>
#include <osmocom/ranap/RANAP_NAS-SynchronisationIndicator.h>
#include <osmocom/ranap/RANAP_Service-Handover.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_RAB_Parameters;
struct RANAP_UserPlaneInformation;
struct RANAP_TransportLayerInformation;
struct RANAP_ProtocolExtensionContainer;

/* RANAP_RAB-SetupOrModifyItemFirst */
typedef struct RANAP_RAB_SetupOrModifyItemFirst {
	RANAP_RAB_ID_t	 rAB_ID;
	RANAP_NAS_SynchronisationIndicator_t	*nAS_SynchronisationIndicator;	/* OPTIONAL */
	struct RANAP_RAB_Parameters	*rAB_Parameters;	/* OPTIONAL */
	struct RANAP_UserPlaneInformation	*userPlaneInformation;	/* OPTIONAL */
	struct RANAP_TransportLayerInformation	*transportLayerInformation;	/* OPTIONAL */
	RANAP_Service_Handover_t	*service_Handover;	/* OPTIONAL */
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_RAB_SetupOrModifyItemFirst_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_RAB_SetupOrModifyItemFirst;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_RAB_SetupOrModifyItemFirst_H_ */
#include <asn_internal.h>
