/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_CellLoadInformation_H_
#define	_RANAP_CellLoadInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_Cell-Capacity-Class-Value.h>
#include <osmocom/ranap/RANAP_LoadValue.h>
#include <osmocom/ranap/RANAP_RTLoadValue.h>
#include <osmocom/ranap/RANAP_NRTLoadInformationValue.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* RANAP_CellLoadInformation */
typedef struct RANAP_CellLoadInformation {
	RANAP_Cell_Capacity_Class_Value_t	 cell_Capacity_Class_Value;
	RANAP_LoadValue_t	 loadValue;
	RANAP_RTLoadValue_t	*rTLoadValue;	/* OPTIONAL */
	RANAP_NRTLoadInformationValue_t	*nRTLoadInformationValue;	/* OPTIONAL */
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_CellLoadInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_CellLoadInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_CellLoadInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_CellLoadInformation_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_CellLoadInformation_H_ */
#include <asn_internal.h>
