/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_DeliveryOfErroneousSDU_H_
#define	_RANAP_DeliveryOfErroneousSDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_DeliveryOfErroneousSDU {
	RANAP_DeliveryOfErroneousSDU_yes	= 0,
	RANAP_DeliveryOfErroneousSDU_no	= 1,
	RANAP_DeliveryOfErroneousSDU_no_error_detection_consideration	= 2
} e_RANAP_DeliveryOfErroneousSDU;

/* RANAP_DeliveryOfErroneousSDU */
typedef long	 RANAP_DeliveryOfErroneousSDU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANAP_DeliveryOfErroneousSDU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANAP_DeliveryOfErroneousSDU;
extern const asn_INTEGER_specifics_t asn_SPC_DeliveryOfErroneousSDU_specs_1;
asn_struct_free_f DeliveryOfErroneousSDU_free;
asn_struct_print_f DeliveryOfErroneousSDU_print;
asn_constr_check_f DeliveryOfErroneousSDU_constraint;
ber_type_decoder_f DeliveryOfErroneousSDU_decode_ber;
der_type_encoder_f DeliveryOfErroneousSDU_encode_der;
xer_type_decoder_f DeliveryOfErroneousSDU_decode_xer;
xer_type_encoder_f DeliveryOfErroneousSDU_encode_xer;
oer_type_decoder_f DeliveryOfErroneousSDU_decode_oer;
oer_type_encoder_f DeliveryOfErroneousSDU_encode_oer;
per_type_decoder_f DeliveryOfErroneousSDU_decode_uper;
per_type_encoder_f DeliveryOfErroneousSDU_encode_uper;
per_type_decoder_f DeliveryOfErroneousSDU_decode_aper;
per_type_encoder_f DeliveryOfErroneousSDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_DeliveryOfErroneousSDU_H_ */
#include <asn_internal.h>
