/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_PositioningPriority_H_
#define	_RANAP_PositioningPriority_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_PositioningPriority {
	RANAP_PositioningPriority_high_Priority	= 0,
	RANAP_PositioningPriority_normal_Priority	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RANAP_PositioningPriority;

/* RANAP_PositioningPriority */
typedef long	 RANAP_PositioningPriority_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANAP_PositioningPriority_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANAP_PositioningPriority;
extern const asn_INTEGER_specifics_t asn_SPC_PositioningPriority_specs_1;
asn_struct_free_f PositioningPriority_free;
asn_struct_print_f PositioningPriority_print;
asn_constr_check_f PositioningPriority_constraint;
ber_type_decoder_f PositioningPriority_decode_ber;
der_type_encoder_f PositioningPriority_encode_der;
xer_type_decoder_f PositioningPriority_decode_xer;
xer_type_encoder_f PositioningPriority_encode_xer;
oer_type_decoder_f PositioningPriority_decode_oer;
oer_type_encoder_f PositioningPriority_encode_oer;
per_type_decoder_f PositioningPriority_decode_uper;
per_type_encoder_f PositioningPriority_encode_uper;
per_type_decoder_f PositioningPriority_decode_aper;
per_type_encoder_f PositioningPriority_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_PositioningPriority_H_ */
#include <asn_internal.h>
