/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_CriticalityDiagnostics_H_
#define	_RANAP_CriticalityDiagnostics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_ProcedureCode.h>
#include <osmocom/ranap/RANAP_TriggeringMessage.h>
#include <osmocom/ranap/RANAP_Criticality.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANAP_CriticalityDiagnostics_IE_List;
struct RANAP_ProtocolExtensionContainer;

/* RANAP_CriticalityDiagnostics */
typedef struct RANAP_CriticalityDiagnostics {
	RANAP_ProcedureCode_t	*procedureCode;	/* OPTIONAL */
	RANAP_TriggeringMessage_t	*triggeringMessage;	/* OPTIONAL */
	RANAP_Criticality_t	*procedureCriticality;	/* OPTIONAL */
	struct RANAP_CriticalityDiagnostics_IE_List	*iEsCriticalityDiagnostics;	/* OPTIONAL */
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_CriticalityDiagnostics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_CriticalityDiagnostics;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_CriticalityDiagnostics_H_ */
#include <asn_internal.h>
