/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_UE_Application_Layer_Measurement_Configuration_H_
#define	_RANAP_UE_Application_Layer_Measurement_Configuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <osmocom/ranap/RANAP_AreaScopeForUEApplicationLayerMeasurementConfiguration.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANAP_UE-Application-Layer-Measurement-Configuration */
typedef struct RANAP_UE_Application_Layer_Measurement_Configuration {
	OCTET_STRING_t	 applicationLayerContainerForMeasurementConfiguration;
	RANAP_AreaScopeForUEApplicationLayerMeasurementConfiguration_t	 areaScopeForUEApplicationLayerMeasurementConfiguration;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_UE_Application_Layer_Measurement_Configuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_UE_Application_Layer_Measurement_Configuration;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_UE_Application_Layer_Measurement_Configuration_H_ */
#include <asn_internal.h>
