/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_InterfacesToTraceItem_H_
#define	_RANAP_InterfacesToTraceItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_InterfacesToTraceItem__interface {
	RANAP_InterfacesToTraceItem__interface_iu_cs	= 0,
	RANAP_InterfacesToTraceItem__interface_iu_ps	= 1,
	RANAP_InterfacesToTraceItem__interface_iur	= 2,
	RANAP_InterfacesToTraceItem__interface_iub	= 3,
	RANAP_InterfacesToTraceItem__interface_uu	= 4
	/*
	 * Enumeration is extensible
	 */
} e_RANAP_InterfacesToTraceItem__interface;

/* Forward declarations */
struct RANAP_ProtocolExtensionContainer;

/* RANAP_InterfacesToTraceItem */
typedef struct RANAP_InterfacesToTraceItem {
	long	 interface;
	struct RANAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_InterfacesToTraceItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_RANAP_interface_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_InterfacesToTraceItem;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_InterfacesToTraceItem_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_InterfacesToTraceItem_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_InterfacesToTraceItem_H_ */
#include <asn_internal.h>
