/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Descriptions"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_UnsuccessfulOutcome_H_
#define	_RANAP_UnsuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_ProcedureCode.h>
#include <osmocom/ranap/RANAP_Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <osmocom/ranap/RANAP_Iu-ReleaseCommand.h>
#include <osmocom/ranap/RANAP_Iu-ReleaseComplete.h>
#include <osmocom/ranap/RANAP_RelocationRequired.h>
#include <osmocom/ranap/RANAP_RelocationCommand.h>
#include <osmocom/ranap/RANAP_RelocationPreparationFailure.h>
#include <osmocom/ranap/RANAP_RelocationRequest.h>
#include <osmocom/ranap/RANAP_RelocationRequestAcknowledge.h>
#include <osmocom/ranap/RANAP_RelocationFailure.h>
#include <osmocom/ranap/RANAP_RelocationCancel.h>
#include <osmocom/ranap/RANAP_RelocationCancelAcknowledge.h>
#include <osmocom/ranap/RANAP_SRNS-ContextRequest.h>
#include <osmocom/ranap/RANAP_SRNS-ContextResponse.h>
#include <osmocom/ranap/RANAP_SecurityModeCommand.h>
#include <osmocom/ranap/RANAP_SecurityModeComplete.h>
#include <osmocom/ranap/RANAP_SecurityModeReject.h>
#include <osmocom/ranap/RANAP_DataVolumeReportRequest.h>
#include <osmocom/ranap/RANAP_DataVolumeReport.h>
#include <osmocom/ranap/RANAP_Reset.h>
#include <osmocom/ranap/RANAP_ResetAcknowledge.h>
#include <osmocom/ranap/RANAP_ResetResource.h>
#include <osmocom/ranap/RANAP_ResetResourceAcknowledge.h>
#include <osmocom/ranap/RANAP_LocationRelatedDataRequest.h>
#include <osmocom/ranap/RANAP_LocationRelatedDataResponse.h>
#include <osmocom/ranap/RANAP_LocationRelatedDataFailure.h>
#include <osmocom/ranap/RANAP_InformationTransferIndication.h>
#include <osmocom/ranap/RANAP_InformationTransferConfirmation.h>
#include <osmocom/ranap/RANAP_InformationTransferFailure.h>
#include <osmocom/ranap/RANAP_UplinkInformationExchangeRequest.h>
#include <osmocom/ranap/RANAP_UplinkInformationExchangeResponse.h>
#include <osmocom/ranap/RANAP_UplinkInformationExchangeFailure.h>
#include <osmocom/ranap/RANAP_MBMSSessionStart.h>
#include <osmocom/ranap/RANAP_MBMSSessionStartResponse.h>
#include <osmocom/ranap/RANAP_MBMSSessionStartFailure.h>
#include <osmocom/ranap/RANAP_MBMSSessionUpdate.h>
#include <osmocom/ranap/RANAP_MBMSSessionUpdateResponse.h>
#include <osmocom/ranap/RANAP_MBMSSessionUpdateFailure.h>
#include <osmocom/ranap/RANAP_MBMSSessionStop.h>
#include <osmocom/ranap/RANAP_MBMSSessionStopResponse.h>
#include <osmocom/ranap/RANAP_MBMSUELinkingRequest.h>
#include <osmocom/ranap/RANAP_MBMSUELinkingResponse.h>
#include <osmocom/ranap/RANAP_MBMSRegistrationRequest.h>
#include <osmocom/ranap/RANAP_MBMSRegistrationResponse.h>
#include <osmocom/ranap/RANAP_MBMSRegistrationFailure.h>
#include <osmocom/ranap/RANAP_MBMSCNDe-RegistrationRequest.h>
#include <osmocom/ranap/RANAP_MBMSCNDe-RegistrationResponse.h>
#include <osmocom/ranap/RANAP_MBMSRABReleaseRequest.h>
#include <osmocom/ranap/RANAP_MBMSRABRelease.h>
#include <osmocom/ranap/RANAP_MBMSRABReleaseFailure.h>
#include <osmocom/ranap/RANAP_EnhancedRelocationCompleteRequest.h>
#include <osmocom/ranap/RANAP_EnhancedRelocationCompleteResponse.h>
#include <osmocom/ranap/RANAP_EnhancedRelocationCompleteFailure.h>
#include <osmocom/ranap/RANAP_RANAP-EnhancedRelocationInformationRequest.h>
#include <osmocom/ranap/RANAP_RANAP-EnhancedRelocationInformationResponse.h>
#include <osmocom/ranap/RANAP_SRVCC-CSKeysRequest.h>
#include <osmocom/ranap/RANAP_SRVCC-CSKeysResponse.h>
#include <osmocom/ranap/RANAP_UeRadioCapabilityMatchRequest.h>
#include <osmocom/ranap/RANAP_UeRadioCapabilityMatchResponse.h>
#include <osmocom/ranap/RANAP_UeRegistrationQueryRequest.h>
#include <osmocom/ranap/RANAP_UeRegistrationQueryResponse.h>
#include <osmocom/ranap/RANAP_RAB-ReleaseRequest.h>
#include <osmocom/ranap/RANAP_Iu-ReleaseRequest.h>
#include <osmocom/ranap/RANAP_RelocationDetect.h>
#include <osmocom/ranap/RANAP_RelocationComplete.h>
#include <osmocom/ranap/RANAP_Paging.h>
#include <osmocom/ranap/RANAP_CommonID.h>
#include <osmocom/ranap/RANAP_CN-InvokeTrace.h>
#include <osmocom/ranap/RANAP_CN-DeactivateTrace.h>
#include <osmocom/ranap/RANAP_LocationReportingControl.h>
#include <osmocom/ranap/RANAP_LocationReport.h>
#include <osmocom/ranap/RANAP_InitialUE-Message.h>
#include <osmocom/ranap/RANAP_DirectTransfer.h>
#include <osmocom/ranap/RANAP_Overload.h>
#include <osmocom/ranap/RANAP_ErrorIndication.h>
#include <osmocom/ranap/RANAP_SRNS-DataForwardCommand.h>
#include <osmocom/ranap/RANAP_ForwardSRNS-Context.h>
#include <osmocom/ranap/RANAP_PrivateMessage.h>
#include <osmocom/ranap/RANAP_RANAP-RelocationInformation.h>
#include <osmocom/ranap/RANAP_RAB-ModifyRequest.h>
#include <osmocom/ranap/RANAP_UESpecificInformationIndication.h>
#include <osmocom/ranap/RANAP_DirectInformationTransfer.h>
#include <osmocom/ranap/RANAP_MBMSRABEstablishmentIndication.h>
#include <osmocom/ranap/RANAP_EnhancedRelocationCompleteConfirm.h>
#include <osmocom/ranap/RANAP_RerouteNASRequest.h>
#include <osmocom/ranap/RANAP_RAB-AssignmentRequest.h>
#include <osmocom/ranap/RANAP_RAB-AssignmentResponse.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_UnsuccessfulOutcome__value_PR {
	RANAP_UnsuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	RANAP_UnsuccessfulOutcome__value_PR_RelocationPreparationFailure,
	RANAP_UnsuccessfulOutcome__value_PR_RelocationFailure,
	RANAP_UnsuccessfulOutcome__value_PR_SecurityModeReject,
	RANAP_UnsuccessfulOutcome__value_PR_LocationRelatedDataFailure,
	RANAP_UnsuccessfulOutcome__value_PR_InformationTransferFailure,
	RANAP_UnsuccessfulOutcome__value_PR_UplinkInformationExchangeFailure,
	RANAP_UnsuccessfulOutcome__value_PR_MBMSSessionStartFailure,
	RANAP_UnsuccessfulOutcome__value_PR_MBMSSessionUpdateFailure,
	RANAP_UnsuccessfulOutcome__value_PR_MBMSRegistrationFailure,
	RANAP_UnsuccessfulOutcome__value_PR_MBMSRABReleaseFailure,
	RANAP_UnsuccessfulOutcome__value_PR_EnhancedRelocationCompleteFailure
} RANAP_UnsuccessfulOutcome__value_PR;

/* RANAP_UnsuccessfulOutcome */
typedef struct RANAP_UnsuccessfulOutcome {
	RANAP_ProcedureCode_t	 procedureCode;
	RANAP_Criticality_t	 criticality;
	struct RANAP_UnsuccessfulOutcome__value {
		RANAP_UnsuccessfulOutcome__value_PR present;
		union RANAP_UnsuccessfulOutcome__RANAP_value_u {
			RANAP_RelocationPreparationFailure_t	 RelocationPreparationFailure;
			RANAP_RelocationFailure_t	 RelocationFailure;
			RANAP_SecurityModeReject_t	 SecurityModeReject;
			RANAP_LocationRelatedDataFailure_t	 LocationRelatedDataFailure;
			RANAP_InformationTransferFailure_t	 InformationTransferFailure;
			RANAP_UplinkInformationExchangeFailure_t	 UplinkInformationExchangeFailure;
			RANAP_MBMSSessionStartFailure_t	 MBMSSessionStartFailure;
			RANAP_MBMSSessionUpdateFailure_t	 MBMSSessionUpdateFailure;
			RANAP_MBMSRegistrationFailure_t	 MBMSRegistrationFailure;
			RANAP_MBMSRABReleaseFailure_t	 MBMSRABReleaseFailure;
			RANAP_EnhancedRelocationCompleteFailure_t	 EnhancedRelocationCompleteFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_UnsuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_UnsuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_RANAP_UnsuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_RANAP_UnsuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_UnsuccessfulOutcome_H_ */
#include <asn_internal.h>
