/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANAP_RelocationType_H_
#define	_RANAP_RelocationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANAP_RelocationType {
	RANAP_RelocationType_ue_not_involved	= 0,
	RANAP_RelocationType_ue_involved	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RANAP_RelocationType;

/* RANAP_RelocationType */
typedef long	 RANAP_RelocationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANAP_RelocationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANAP_RelocationType;
extern const asn_INTEGER_specifics_t asn_SPC_RelocationType_specs_1;
asn_struct_free_f RelocationType_free;
asn_struct_print_f RelocationType_print;
asn_constr_check_f RelocationType_constraint;
ber_type_decoder_f RelocationType_decode_ber;
der_type_encoder_f RelocationType_encode_der;
xer_type_decoder_f RelocationType_decode_xer;
xer_type_encoder_f RelocationType_encode_xer;
oer_type_decoder_f RelocationType_decode_oer;
oer_type_encoder_f RelocationType_encode_oer;
per_type_decoder_f RelocationType_decode_uper;
per_type_encoder_f RelocationType_encode_uper;
per_type_decoder_f RelocationType_decode_aper;
per_type_encoder_f RelocationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_RelocationType_H_ */
#include <asn_internal.h>
