/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_AltitudeAndDirection_H_
#define	_AltitudeAndDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AltitudeAndDirection__directionOfAltitude {
	AltitudeAndDirection__directionOfAltitude_height	= 0,
	AltitudeAndDirection__directionOfAltitude_depth	= 1
} e_AltitudeAndDirection__directionOfAltitude;

/* AltitudeAndDirection */
typedef struct AltitudeAndDirection {
	long	 directionOfAltitude;
	long	 altitude;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AltitudeAndDirection_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_directionOfAltitude_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_AltitudeAndDirection;
extern asn_SEQUENCE_specifics_t asn_SPC_AltitudeAndDirection_specs_1;
extern asn_TYPE_member_t asn_MBR_AltitudeAndDirection_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AltitudeAndDirection_H_ */
#include <asn_internal.h>
