/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_HNB_Cell_Access_Mode_H_
#define	_HNB_Cell_Access_Mode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNB_Cell_Access_Mode {
	HNB_Cell_Access_Mode_closed	= 0,
	HNB_Cell_Access_Mode_hybrid	= 1,
	HNB_Cell_Access_Mode_open	= 2
	/*
	 * Enumeration is extensible
	 */
} e_HNB_Cell_Access_Mode;

/* HNB-Cell-Access-Mode */
typedef long	 HNB_Cell_Access_Mode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HNB_Cell_Access_Mode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HNB_Cell_Access_Mode;
extern const asn_INTEGER_specifics_t asn_SPC_HNB_Cell_Access_Mode_specs_1;
asn_struct_free_f HNB_Cell_Access_Mode_free;
asn_struct_print_f HNB_Cell_Access_Mode_print;
asn_constr_check_f HNB_Cell_Access_Mode_constraint;
ber_type_decoder_f HNB_Cell_Access_Mode_decode_ber;
der_type_encoder_f HNB_Cell_Access_Mode_encode_der;
xer_type_decoder_f HNB_Cell_Access_Mode_decode_xer;
xer_type_encoder_f HNB_Cell_Access_Mode_encode_xer;
oer_type_decoder_f HNB_Cell_Access_Mode_decode_oer;
oer_type_encoder_f HNB_Cell_Access_Mode_encode_oer;
per_type_decoder_f HNB_Cell_Access_Mode_decode_uper;
per_type_encoder_f HNB_Cell_Access_Mode_encode_uper;
per_type_decoder_f HNB_Cell_Access_Mode_decode_aper;
per_type_encoder_f HNB_Cell_Access_Mode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNB_Cell_Access_Mode_H_ */
#include <asn_internal.h>
