/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_IP_Address_H_
#define	_IP_Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/Ipv4Address.h>
#include <osmocom/hnbap/Ipv6Address.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IP_Address__ipaddress_PR {
	IP_Address__ipaddress_PR_NOTHING,	/* No components present */
	IP_Address__ipaddress_PR_ipv4info,
	IP_Address__ipaddress_PR_ipv6info
	/* Extensions may appear below */
	
} IP_Address__ipaddress_PR;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* IP-Address */
typedef struct IP_Address {
	struct IP_Address__ipaddress {
		IP_Address__ipaddress_PR present;
		union IP_Address__ipaddress_u {
			Ipv4Address_t	 ipv4info;
			Ipv6Address_t	 ipv6info;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ipaddress;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IP_Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IP_Address;
extern asn_SEQUENCE_specifics_t asn_SPC_IP_Address_specs_1;
extern asn_TYPE_member_t asn_MBR_IP_Address_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _IP_Address_H_ */
#include <asn_internal.h>
