/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_ProtocolIE_ID_H_
#define	_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-ID */
typedef long	 ProtocolIE_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ID;
asn_struct_free_f ProtocolIE_ID_free;
asn_struct_print_f ProtocolIE_ID_print;
asn_constr_check_f ProtocolIE_ID_constraint;
ber_type_decoder_f ProtocolIE_ID_decode_ber;
der_type_encoder_f ProtocolIE_ID_encode_der;
xer_type_decoder_f ProtocolIE_ID_decode_xer;
xer_type_encoder_f ProtocolIE_ID_encode_xer;
oer_type_decoder_f ProtocolIE_ID_decode_oer;
oer_type_encoder_f ProtocolIE_ID_encode_oer;
per_type_decoder_f ProtocolIE_ID_decode_uper;
per_type_encoder_f ProtocolIE_ID_encode_uper;
per_type_decoder_f ProtocolIE_ID_decode_aper;
per_type_encoder_f ProtocolIE_ID_encode_aper;
#define ProtocolIE_ID_id_Cause	((ProtocolIE_ID_t)1)
#define ProtocolIE_ID_id_CriticalityDiagnostics	((ProtocolIE_ID_t)2)
#define ProtocolIE_ID_id_HNB_Identity	((ProtocolIE_ID_t)3)
#define ProtocolIE_ID_id_Context_ID	((ProtocolIE_ID_t)4)
#define ProtocolIE_ID_id_UE_Identity	((ProtocolIE_ID_t)5)
#define ProtocolIE_ID_id_LAC	((ProtocolIE_ID_t)6)
#define ProtocolIE_ID_id_RAC	((ProtocolIE_ID_t)7)
#define ProtocolIE_ID_id_HNB_Location_Information	((ProtocolIE_ID_t)8)
#define ProtocolIE_ID_id_PLMNidentity	((ProtocolIE_ID_t)9)
#define ProtocolIE_ID_id_SAC	((ProtocolIE_ID_t)10)
#define ProtocolIE_ID_id_CellIdentity	((ProtocolIE_ID_t)11)
#define ProtocolIE_ID_id_Registration_Cause	((ProtocolIE_ID_t)12)
#define ProtocolIE_ID_id_UE_Capabilities	((ProtocolIE_ID_t)13)
#define ProtocolIE_ID_id_RNC_ID	((ProtocolIE_ID_t)14)
#define ProtocolIE_ID_id_CSG_ID	((ProtocolIE_ID_t)15)
#define ProtocolIE_ID_id_BackoffTimer	((ProtocolIE_ID_t)16)
#define ProtocolIE_ID_id_HNB_Internet_Information	((ProtocolIE_ID_t)17)
#define ProtocolIE_ID_id_HNB_Cell_Access_Mode	((ProtocolIE_ID_t)18)
#define ProtocolIE_ID_id_MuxPortNumber	((ProtocolIE_ID_t)19)
#define ProtocolIE_ID_id_Service_Area_For_Broadcast	((ProtocolIE_ID_t)20)
#define ProtocolIE_ID_id_CSGMembershipStatus	((ProtocolIE_ID_t)21)
#define ProtocolIE_ID_id_RABList	((ProtocolIE_ID_t)22)
#define ProtocolIE_ID_id_HNBConfigInfo	((ProtocolIE_ID_t)23)
#define ProtocolIE_ID_id_AccessResult	((ProtocolIE_ID_t)25)
#define ProtocolIE_ID_id_Update_cause	((ProtocolIE_ID_t)26)
#define ProtocolIE_ID_id_NeighbourInfoList	((ProtocolIE_ID_t)27)
#define ProtocolIE_ID_id_NeighbourInfoRequestList	((ProtocolIE_ID_t)28)
#define ProtocolIE_ID_id_Iurh_Signalling_TNL_Address	((ProtocolIE_ID_t)29)
#define ProtocolIE_ID_id_PSC	((ProtocolIE_ID_t)30)
#define ProtocolIE_ID_id_HNB_Cell_Identifier	((ProtocolIE_ID_t)31)
#define ProtocolIE_ID_id_Tunnel_Information	((ProtocolIE_ID_t)41)
#define ProtocolIE_ID_id_CELL_FACHMobilitySupport	((ProtocolIE_ID_t)42)
#define ProtocolIE_ID_id_S_RNTIPrefix	((ProtocolIE_ID_t)43)
#define ProtocolIE_ID_id_URAIdentity	((ProtocolIE_ID_t)44)
#define ProtocolIE_ID_id_NeighbourIdentity	((ProtocolIE_ID_t)45)
#define ProtocolIE_ID_id_HNBCapacity	((ProtocolIE_ID_t)46)
#define ProtocolIE_ID_id_NeighbourCellIdentityList	((ProtocolIE_ID_t)47)
#define ProtocolIE_ID_id_AdditionalNeighbourInfoList	((ProtocolIE_ID_t)48)
#define ProtocolIE_ID_id_U_RNTI	((ProtocolIE_ID_t)49)
#define ProtocolIE_ID_id_UnknownU_RNTIIndication	((ProtocolIE_ID_t)50)
#define ProtocolIE_ID_id_HNB_GWResponse	((ProtocolIE_ID_t)51)
#define ProtocolIE_ID_id_URAIdentityList	((ProtocolIE_ID_t)52)

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ID_H_ */
#include <asn_internal.h>
