/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-Containers"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_ProtocolIE_Field_H_
#define	_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/ProtocolIE-ID.h>
#include <osmocom/hnbap/Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <osmocom/hnbap/HNB-Identity.h>
#include <osmocom/hnbap/Presence.h>
#include <osmocom/hnbap/HNB-Location-Information.h>
#include <osmocom/hnbap/PLMNidentity.h>
#include <osmocom/hnbap/CellIdentity.h>
#include <osmocom/hnbap/LAC.h>
#include <osmocom/hnbap/RAC.h>
#include <osmocom/hnbap/SAC.h>
#include <osmocom/hnbap/CSG-ID.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <osmocom/hnbap/RNC-ID.h>
#include <osmocom/hnbap/Cause.h>
#include <osmocom/hnbap/CriticalityDiagnostics.h>
#include <osmocom/hnbap/BackoffTimer.h>
#include <osmocom/hnbap/UE-Identity.h>
#include <osmocom/hnbap/Registration-Cause.h>
#include <osmocom/hnbap/UE-Capabilities.h>
#include <osmocom/hnbap/Context-ID.h>
#include <osmocom/hnbap/CSGMembershipStatus.h>
#include <osmocom/hnbap/RABList.h>
#include <osmocom/hnbap/Update-cause.h>
#include <osmocom/hnbap/NeighbourInfoRequestList.h>
#include <osmocom/hnbap/NeighbourInfoList.h>
#include <osmocom/hnbap/U-RNTI.h>
#include <osmocom/hnbap/HNB-GWResponse.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBRegisterRequestIEs__value_PR {
	HNBRegisterRequestIEs__value_PR_NOTHING,	/* No components present */
	HNBRegisterRequestIEs__value_PR_HNB_Identity,
	HNBRegisterRequestIEs__value_PR_HNB_Location_Information,
	HNBRegisterRequestIEs__value_PR_PLMNidentity,
	HNBRegisterRequestIEs__value_PR_CellIdentity,
	HNBRegisterRequestIEs__value_PR_LAC,
	HNBRegisterRequestIEs__value_PR_RAC,
	HNBRegisterRequestIEs__value_PR_SAC,
	HNBRegisterRequestIEs__value_PR_CSG_ID
} HNBRegisterRequestIEs__value_PR;
typedef enum HNBRegisterResponseIEs__value_PR {
	HNBRegisterResponseIEs__value_PR_NOTHING,	/* No components present */
	HNBRegisterResponseIEs__value_PR_RNC_ID
} HNBRegisterResponseIEs__value_PR;
typedef enum HNBRegisterRejectIEs__value_PR {
	HNBRegisterRejectIEs__value_PR_NOTHING,	/* No components present */
	HNBRegisterRejectIEs__value_PR_Cause,
	HNBRegisterRejectIEs__value_PR_CriticalityDiagnostics,
	HNBRegisterRejectIEs__value_PR_BackoffTimer
} HNBRegisterRejectIEs__value_PR;
typedef enum HNBDe_RegisterIEs__value_PR {
	HNBDe_RegisterIEs__value_PR_NOTHING,	/* No components present */
	HNBDe_RegisterIEs__value_PR_Cause,
	HNBDe_RegisterIEs__value_PR_BackoffTimer
} HNBDe_RegisterIEs__value_PR;
typedef enum UERegisterRequestIEs__value_PR {
	UERegisterRequestIEs__value_PR_NOTHING,	/* No components present */
	UERegisterRequestIEs__value_PR_UE_Identity,
	UERegisterRequestIEs__value_PR_Registration_Cause,
	UERegisterRequestIEs__value_PR_UE_Capabilities
} UERegisterRequestIEs__value_PR;
typedef enum UERegisterAcceptIEs__value_PR {
	UERegisterAcceptIEs__value_PR_NOTHING,	/* No components present */
	UERegisterAcceptIEs__value_PR_UE_Identity,
	UERegisterAcceptIEs__value_PR_Context_ID
} UERegisterAcceptIEs__value_PR;
typedef enum UERegisterRejectIEs__value_PR {
	UERegisterRejectIEs__value_PR_NOTHING,	/* No components present */
	UERegisterRejectIEs__value_PR_UE_Identity,
	UERegisterRejectIEs__value_PR_Cause,
	UERegisterRejectIEs__value_PR_CriticalityDiagnostics
} UERegisterRejectIEs__value_PR;
typedef enum UEDe_RegisterIEs__value_PR {
	UEDe_RegisterIEs__value_PR_NOTHING,	/* No components present */
	UEDe_RegisterIEs__value_PR_Context_ID,
	UEDe_RegisterIEs__value_PR_Cause
} UEDe_RegisterIEs__value_PR;
typedef enum CSGMembershipUpdateIEs__value_PR {
	CSGMembershipUpdateIEs__value_PR_NOTHING,	/* No components present */
	CSGMembershipUpdateIEs__value_PR_Context_ID,
	CSGMembershipUpdateIEs__value_PR_CSGMembershipStatus
} CSGMembershipUpdateIEs__value_PR;
typedef enum TNLUpdateRequestIEs__value_PR {
	TNLUpdateRequestIEs__value_PR_NOTHING,	/* No components present */
	TNLUpdateRequestIEs__value_PR_Context_ID,
	TNLUpdateRequestIEs__value_PR_RABList,
	TNLUpdateRequestIEs__value_PR_Update_cause
} TNLUpdateRequestIEs__value_PR;
typedef enum TNLUpdateResponseIEs__value_PR {
	TNLUpdateResponseIEs__value_PR_NOTHING,	/* No components present */
	TNLUpdateResponseIEs__value_PR_Context_ID
} TNLUpdateResponseIEs__value_PR;
typedef enum TNLUpdateFailureIEs__value_PR {
	TNLUpdateFailureIEs__value_PR_NOTHING,	/* No components present */
	TNLUpdateFailureIEs__value_PR_Context_ID,
	TNLUpdateFailureIEs__value_PR_Cause,
	TNLUpdateFailureIEs__value_PR_CriticalityDiagnostics
} TNLUpdateFailureIEs__value_PR;
typedef enum HNBConfigTransferRequestIEs__value_PR {
	HNBConfigTransferRequestIEs__value_PR_NOTHING,	/* No components present */
	HNBConfigTransferRequestIEs__value_PR_NeighbourInfoRequestList
} HNBConfigTransferRequestIEs__value_PR;
typedef enum HNBConfigTransferResponseIEs__value_PR {
	HNBConfigTransferResponseIEs__value_PR_NOTHING,	/* No components present */
	HNBConfigTransferResponseIEs__value_PR_NeighbourInfoList
} HNBConfigTransferResponseIEs__value_PR;
typedef enum RelocationCompleteIEs__value_PR {
	RelocationCompleteIEs__value_PR_NOTHING,	/* No components present */
	RelocationCompleteIEs__value_PR_Context_ID
} RelocationCompleteIEs__value_PR;
typedef enum ErrorIndicationIEs__value_PR {
	ErrorIndicationIEs__value_PR_NOTHING,	/* No components present */
	ErrorIndicationIEs__value_PR_Cause,
	ErrorIndicationIEs__value_PR_CriticalityDiagnostics
} ErrorIndicationIEs__value_PR;
typedef enum U_RNTIQueryRequestIEs__value_PR {
	U_RNTIQueryRequestIEs__value_PR_NOTHING,	/* No components present */
	U_RNTIQueryRequestIEs__value_PR_U_RNTI
} U_RNTIQueryRequestIEs__value_PR;
typedef enum U_RNTIQueryResponseIEs__value_PR {
	U_RNTIQueryResponseIEs__value_PR_NOTHING,	/* No components present */
	U_RNTIQueryResponseIEs__value_PR_HNB_GWResponse
} U_RNTIQueryResponseIEs__value_PR;

/* ProtocolIE-Field */
typedef struct HNBRegisterRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBRegisterRequestIEs__value {
		HNBRegisterRequestIEs__value_PR present;
		union HNBRegisterRequestIEs__value_u {
			HNB_Identity_t	 HNB_Identity;
			HNB_Location_Information_t	 HNB_Location_Information;
			PLMNidentity_t	 PLMNidentity;
			CellIdentity_t	 CellIdentity;
			LAC_t	 LAC;
			RAC_t	 RAC;
			SAC_t	 SAC;
			CSG_ID_t	 CSG_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBRegisterRequestIEs_t;
typedef struct HNBRegisterResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBRegisterResponseIEs__value {
		HNBRegisterResponseIEs__value_PR present;
		union HNBRegisterResponseIEs__value_u {
			RNC_ID_t	 RNC_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBRegisterResponseIEs_t;
typedef struct HNBRegisterRejectIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBRegisterRejectIEs__value {
		HNBRegisterRejectIEs__value_PR present;
		union HNBRegisterRejectIEs__value_u {
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
			BackoffTimer_t	 BackoffTimer;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBRegisterRejectIEs_t;
typedef struct HNBDe_RegisterIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBDe_RegisterIEs__value {
		HNBDe_RegisterIEs__value_PR present;
		union HNBDe_RegisterIEs__value_u {
			Cause_t	 Cause;
			BackoffTimer_t	 BackoffTimer;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBDe_RegisterIEs_t;
typedef struct UERegisterRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UERegisterRequestIEs__value {
		UERegisterRequestIEs__value_PR present;
		union UERegisterRequestIEs__value_u {
			UE_Identity_t	 UE_Identity;
			Registration_Cause_t	 Registration_Cause;
			UE_Capabilities_t	 UE_Capabilities;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERegisterRequestIEs_t;
typedef struct UERegisterAcceptIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UERegisterAcceptIEs__value {
		UERegisterAcceptIEs__value_PR present;
		union UERegisterAcceptIEs__value_u {
			UE_Identity_t	 UE_Identity;
			Context_ID_t	 Context_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERegisterAcceptIEs_t;
typedef struct UERegisterRejectIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UERegisterRejectIEs__value {
		UERegisterRejectIEs__value_PR present;
		union UERegisterRejectIEs__value_u {
			UE_Identity_t	 UE_Identity;
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERegisterRejectIEs_t;
typedef struct UEDe_RegisterIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UEDe_RegisterIEs__value {
		UEDe_RegisterIEs__value_PR present;
		union UEDe_RegisterIEs__value_u {
			Context_ID_t	 Context_ID;
			Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEDe_RegisterIEs_t;
typedef struct CSGMembershipUpdateIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct CSGMembershipUpdateIEs__value {
		CSGMembershipUpdateIEs__value_PR present;
		union CSGMembershipUpdateIEs__value_u {
			Context_ID_t	 Context_ID;
			CSGMembershipStatus_t	 CSGMembershipStatus;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSGMembershipUpdateIEs_t;
typedef struct TNLUpdateRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct TNLUpdateRequestIEs__value {
		TNLUpdateRequestIEs__value_PR present;
		union TNLUpdateRequestIEs__value_u {
			Context_ID_t	 Context_ID;
			RABList_t	 RABList;
			Update_cause_t	 Update_cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TNLUpdateRequestIEs_t;
typedef struct TNLUpdateResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct TNLUpdateResponseIEs__value {
		TNLUpdateResponseIEs__value_PR present;
		union TNLUpdateResponseIEs__value_u {
			Context_ID_t	 Context_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TNLUpdateResponseIEs_t;
typedef struct TNLUpdateFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct TNLUpdateFailureIEs__value {
		TNLUpdateFailureIEs__value_PR present;
		union TNLUpdateFailureIEs__value_u {
			Context_ID_t	 Context_ID;
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TNLUpdateFailureIEs_t;
typedef struct HNBConfigTransferRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBConfigTransferRequestIEs__value {
		HNBConfigTransferRequestIEs__value_PR present;
		union HNBConfigTransferRequestIEs__value_u {
			NeighbourInfoRequestList_t	 NeighbourInfoRequestList;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBConfigTransferRequestIEs_t;
typedef struct HNBConfigTransferResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct HNBConfigTransferResponseIEs__value {
		HNBConfigTransferResponseIEs__value_PR present;
		union HNBConfigTransferResponseIEs__value_u {
			NeighbourInfoList_t	 NeighbourInfoList;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBConfigTransferResponseIEs_t;
typedef struct RelocationCompleteIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct RelocationCompleteIEs__value {
		RelocationCompleteIEs__value_PR present;
		union RelocationCompleteIEs__value_u {
			Context_ID_t	 Context_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RelocationCompleteIEs_t;
typedef struct ErrorIndicationIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ErrorIndicationIEs__value {
		ErrorIndicationIEs__value_PR present;
		union ErrorIndicationIEs__value_u {
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ErrorIndicationIEs_t;
typedef struct U_RNTIQueryRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct U_RNTIQueryRequestIEs__value {
		U_RNTIQueryRequestIEs__value_PR present;
		union U_RNTIQueryRequestIEs__value_u {
			U_RNTI_t	 U_RNTI;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} U_RNTIQueryRequestIEs_t;
typedef struct U_RNTIQueryResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct U_RNTIQueryResponseIEs__value {
		U_RNTIQueryResponseIEs__value_PR present;
		union U_RNTIQueryResponseIEs__value_u {
			HNB_GWResponse_t	 HNB_GWResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} U_RNTIQueryResponseIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBRegisterRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBRegisterRequestIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_HNBRegisterRequestIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_HNBRegisterResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBRegisterResponseIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_HNBRegisterResponseIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_HNBRegisterRejectIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBRegisterRejectIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_HNBRegisterRejectIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_HNBDe_RegisterIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBDe_RegisterIEs_specs_13;
extern asn_TYPE_member_t asn_MBR_HNBDe_RegisterIEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_UERegisterRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UERegisterRequestIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_UERegisterRequestIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_UERegisterAcceptIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UERegisterAcceptIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_UERegisterAcceptIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_UERegisterRejectIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UERegisterRejectIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_UERegisterRejectIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_UEDe_RegisterIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEDe_RegisterIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_UEDe_RegisterIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_CSGMembershipUpdateIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_CSGMembershipUpdateIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_CSGMembershipUpdateIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_TNLUpdateRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TNLUpdateRequestIEs_specs_37;
extern asn_TYPE_member_t asn_MBR_TNLUpdateRequestIEs_37[3];
extern asn_TYPE_descriptor_t asn_DEF_TNLUpdateResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TNLUpdateResponseIEs_specs_41;
extern asn_TYPE_member_t asn_MBR_TNLUpdateResponseIEs_41[3];
extern asn_TYPE_descriptor_t asn_DEF_TNLUpdateFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TNLUpdateFailureIEs_specs_45;
extern asn_TYPE_member_t asn_MBR_TNLUpdateFailureIEs_45[3];
extern asn_TYPE_descriptor_t asn_DEF_HNBConfigTransferRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBConfigTransferRequestIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_HNBConfigTransferRequestIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_HNBConfigTransferResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HNBConfigTransferResponseIEs_specs_53;
extern asn_TYPE_member_t asn_MBR_HNBConfigTransferResponseIEs_53[3];
extern asn_TYPE_descriptor_t asn_DEF_RelocationCompleteIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RelocationCompleteIEs_specs_57;
extern asn_TYPE_member_t asn_MBR_RelocationCompleteIEs_57[3];
extern asn_TYPE_descriptor_t asn_DEF_ErrorIndicationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ErrorIndicationIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_ErrorIndicationIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_U_RNTIQueryRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_U_RNTIQueryRequestIEs_specs_65;
extern asn_TYPE_member_t asn_MBR_U_RNTIQueryRequestIEs_65[3];
extern asn_TYPE_descriptor_t asn_DEF_U_RNTIQueryResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_U_RNTIQueryResponseIEs_specs_69;
extern asn_TYPE_member_t asn_MBR_U_RNTIQueryResponseIEs_69[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Field_H_ */
#include <asn_internal.h>
