/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RABListItem_H_
#define	_RABListItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/RAB-ID.h>
#include <osmocom/hnbap/TransportInfo.h>
#include <osmocom/hnbap/CN-DomainIndicator.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RABListItem */
typedef struct RABListItem {
	RAB_ID_t	 rAB_ID;
	TransportInfo_t	 old_transport_Info;
	TransportInfo_t	 new_transport_Info;
	CN_DomainIndicator_t	 cn_domain_indicator;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RABListItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RABListItem;
extern asn_SEQUENCE_specifics_t asn_SPC_RABListItem_specs_1;
extern asn_TYPE_member_t asn_MBR_RABListItem_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RABListItem_H_ */
#include <asn_internal.h>
