/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_S_RNTIPrefix_H_
#define	_S_RNTIPrefix_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S-RNTIPrefix */
typedef BIT_STRING_t	 S_RNTIPrefix_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S_RNTIPrefix;
asn_struct_free_f S_RNTIPrefix_free;
asn_struct_print_f S_RNTIPrefix_print;
asn_constr_check_f S_RNTIPrefix_constraint;
ber_type_decoder_f S_RNTIPrefix_decode_ber;
der_type_encoder_f S_RNTIPrefix_encode_der;
xer_type_decoder_f S_RNTIPrefix_decode_xer;
xer_type_encoder_f S_RNTIPrefix_encode_xer;
oer_type_decoder_f S_RNTIPrefix_decode_oer;
oer_type_encoder_f S_RNTIPrefix_encode_oer;
per_type_decoder_f S_RNTIPrefix_decode_uper;
per_type_encoder_f S_RNTIPrefix_encode_uper;
per_type_decoder_f S_RNTIPrefix_decode_aper;
per_type_encoder_f S_RNTIPrefix_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _S_RNTIPrefix_H_ */
#include <asn_internal.h>
