/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-Containers"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/rua/RUA_ProtocolIE-Field.h>

static const long asn_VAL_1_RUA_id_CN_DomainIndicator = 7;
static const long asn_VAL_1_RUA_reject = 0;
static const long asn_VAL_1_RUA_mandatory = 2;
static const long asn_VAL_2_RUA_id_Context_ID = 3;
static const long asn_VAL_2_RUA_reject = 0;
static const long asn_VAL_2_RUA_mandatory = 2;
static const long asn_VAL_3_RUA_id_IntraDomainNasNodeSelector = 5;
static const long asn_VAL_3_RUA_ignore = 1;
static const long asn_VAL_3_RUA_optional = 0;
static const long asn_VAL_4_RUA_id_Establishment_Cause = 6;
static const long asn_VAL_4_RUA_reject = 0;
static const long asn_VAL_4_RUA_mandatory = 2;
static const long asn_VAL_5_RUA_id_RANAP_Message = 4;
static const long asn_VAL_5_RUA_reject = 0;
static const long asn_VAL_5_RUA_mandatory = 2;
static const asn_ioc_cell_t asn_IOS_RUA_ConnectIEs_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_1_RUA_id_CN_DomainIndicator },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_1_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_CN_DomainIndicator },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_1_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_2_RUA_id_Context_ID },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_2_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_Context_ID },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_2_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_3_RUA_id_IntraDomainNasNodeSelector },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_3_RUA_ignore },
	{ "&Value", aioc__type, &asn_DEF_RUA_IntraDomainNasNodeSelector },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_3_RUA_optional },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_4_RUA_id_Establishment_Cause },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_4_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_Establishment_Cause },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_4_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_5_RUA_id_RANAP_Message },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_5_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_RANAP_Message },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_5_RUA_mandatory }
};
static const asn_ioc_set_t asn_IOS_RUA_ConnectIEs_1[] = {
	{ 5, 4, asn_IOS_RUA_ConnectIEs_1_rows }
};
static const long asn_VAL_6_RUA_id_CN_DomainIndicator = 7;
static const long asn_VAL_6_RUA_reject = 0;
static const long asn_VAL_6_RUA_mandatory = 2;
static const long asn_VAL_7_RUA_id_Context_ID = 3;
static const long asn_VAL_7_RUA_reject = 0;
static const long asn_VAL_7_RUA_mandatory = 2;
static const long asn_VAL_8_RUA_id_RANAP_Message = 4;
static const long asn_VAL_8_RUA_reject = 0;
static const long asn_VAL_8_RUA_mandatory = 2;
static const asn_ioc_cell_t asn_IOS_RUA_DirectTransferIEs_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_6_RUA_id_CN_DomainIndicator },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_6_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_CN_DomainIndicator },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_6_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_7_RUA_id_Context_ID },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_7_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_Context_ID },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_7_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_8_RUA_id_RANAP_Message },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_8_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_RANAP_Message },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_8_RUA_mandatory }
};
static const asn_ioc_set_t asn_IOS_RUA_DirectTransferIEs_1[] = {
	{ 3, 4, asn_IOS_RUA_DirectTransferIEs_1_rows }
};
static const long asn_VAL_9_RUA_id_CN_DomainIndicator = 7;
static const long asn_VAL_9_RUA_reject = 0;
static const long asn_VAL_9_RUA_mandatory = 2;
static const long asn_VAL_10_RUA_id_Context_ID = 3;
static const long asn_VAL_10_RUA_reject = 0;
static const long asn_VAL_10_RUA_mandatory = 2;
static const long asn_VAL_11_RUA_id_Cause = 1;
static const long asn_VAL_11_RUA_reject = 0;
static const long asn_VAL_11_RUA_mandatory = 2;
static const long asn_VAL_12_RUA_id_RANAP_Message = 4;
static const long asn_VAL_12_RUA_reject = 0;
static const long asn_VAL_12_RUA_conditional = 1;
static const asn_ioc_cell_t asn_IOS_RUA_DisconnectIEs_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_9_RUA_id_CN_DomainIndicator },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_9_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_CN_DomainIndicator },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_9_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_10_RUA_id_Context_ID },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_10_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_Context_ID },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_10_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_11_RUA_id_Cause },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_11_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_Cause },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_11_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_12_RUA_id_RANAP_Message },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_12_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_RANAP_Message },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_12_RUA_conditional }
};
static const asn_ioc_set_t asn_IOS_RUA_DisconnectIEs_1[] = {
	{ 4, 4, asn_IOS_RUA_DisconnectIEs_1_rows }
};
static const long asn_VAL_13_RUA_id_RANAP_Message = 4;
static const long asn_VAL_13_RUA_reject = 0;
static const long asn_VAL_13_RUA_mandatory = 2;
static const asn_ioc_cell_t asn_IOS_RUA_ConnectionlessTransferIEs_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_13_RUA_id_RANAP_Message },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_13_RUA_reject },
	{ "&Value", aioc__type, &asn_DEF_RUA_RANAP_Message },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_13_RUA_mandatory }
};
static const asn_ioc_set_t asn_IOS_RUA_ConnectionlessTransferIEs_1[] = {
	{ 1, 4, asn_IOS_RUA_ConnectionlessTransferIEs_1_rows }
};
static const long asn_VAL_14_RUA_id_Cause = 1;
static const long asn_VAL_14_RUA_ignore = 1;
static const long asn_VAL_14_RUA_mandatory = 2;
static const long asn_VAL_15_RUA_id_CriticalityDiagnostics = 2;
static const long asn_VAL_15_RUA_ignore = 1;
static const long asn_VAL_15_RUA_optional = 0;
static const asn_ioc_cell_t asn_IOS_RUA_ErrorIndicationIEs_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_14_RUA_id_Cause },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_14_RUA_ignore },
	{ "&Value", aioc__type, &asn_DEF_RUA_Cause },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_14_RUA_mandatory },
	{ "&id", aioc__value, &asn_DEF_RUA_ProtocolIE_ID, &asn_VAL_15_RUA_id_CriticalityDiagnostics },
	{ "&criticality", aioc__value, &asn_DEF_RUA_Criticality, &asn_VAL_15_RUA_ignore },
	{ "&Value", aioc__type, &asn_DEF_RUA_CriticalityDiagnostics },
	{ "&presence", aioc__value, &asn_DEF_RUA_Presence, &asn_VAL_15_RUA_optional }
};
static const asn_ioc_set_t asn_IOS_RUA_ErrorIndicationIEs_1[] = {
	{ 2, 4, asn_IOS_RUA_ErrorIndicationIEs_1_rows }
};
static int
memb_RUA_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_ConnectIEs_RUA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ConnectIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ConnectIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_ConnectIEs_RUA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ConnectIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 2; /* &Value */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ConnectIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_RUA_id_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_DirectTransferIEs_RUA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_DirectTransferIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_DirectTransferIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_criticality_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_DirectTransferIEs_RUA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_DirectTransferIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 2; /* &Value */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_DirectTransferIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_value_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_RUA_id_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_DisconnectIEs_RUA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_DisconnectIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_DisconnectIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_criticality_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_DisconnectIEs_RUA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_DisconnectIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 2; /* &Value */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_DisconnectIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_value_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_RUA_id_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_ConnectionlessTransferIEs_RUA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ConnectionlessTransferIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ConnectionlessTransferIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_criticality_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_ConnectionlessTransferIEs_RUA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ConnectionlessTransferIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 2; /* &Value */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ConnectionlessTransferIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_value_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_RUA_id_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_ErrorIndicationIEs_RUA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ErrorIndicationIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ErrorIndicationIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_criticality_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_ErrorIndicationIEs_RUA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_RUA_ErrorIndicationIEs_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 2; /* &Value */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct RUA_ErrorIndicationIEs, id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_RUA_value_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_RUA_id_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_id_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_criticality_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_value_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_id_constr_6 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_id_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_criticality_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_criticality_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_value_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_value_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_id_constr_10 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_id_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_criticality_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_criticality_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_value_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_value_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_id_constr_14 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_id_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_criticality_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_criticality_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_value_constr_16 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_value_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_id_constr_18 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_id_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_criticality_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_criticality_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RUA_value_constr_20 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_RUA_value_constr_20 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RUA_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs__value, choice.CN_DomainIndicator),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_RUA_CN_DomainIndicator,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CN-DomainIndicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs__value, choice.Context_ID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_RUA_Context_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Context-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs__value, choice.IntraDomainNasNodeSelector),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_IntraDomainNasNodeSelector,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IntraDomainNasNodeSelector"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs__value, choice.Establishment_Cause),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_RUA_Establishment_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Establishment-Cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs__value, choice.RANAP_Message),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RUA_RANAP_Message,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANAP-Message"
		},
};
static const unsigned asn_MAP_RUA_value_to_canonical_4[] = { 1, 4, 0, 3, 2 };
static const unsigned asn_MAP_RUA_value_from_canonical_4[] = { 2, 0, 4, 3, 1 };
static const asn_TYPE_tag2member_t asn_MAP_RUA_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* Context-ID */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, 0, 0 }, /* RANAP-Message */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 1 }, /* CN-DomainIndicator */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 3, -1, 0 }, /* Establishment-Cause */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* IntraDomainNasNodeSelector */
};
static asn_CHOICE_specifics_t asn_SPC_RUA_value_specs_4 = {
	sizeof(struct RUA_ConnectIEs__value),
	offsetof(struct RUA_ConnectIEs__value, _asn_ctx),
	offsetof(struct RUA_ConnectIEs__value, present),
	sizeof(((struct RUA_ConnectIEs__value *)0)->present),
	asn_MAP_RUA_value_tag2el_4,
	5,	/* Count of tags in the map */
	asn_MAP_RUA_value_to_canonical_4,
	asn_MAP_RUA_value_from_canonical_4,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RUA_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_RUA_value_4,
	5,	/* Elements count */
	&asn_SPC_RUA_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ConnectIEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_ProtocolIE_ID,
		0,
		{ &asn_OER_memb_RUA_id_constr_2, &asn_PER_memb_RUA_id_constr_2,  memb_RUA_id_constraint_1 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_Criticality,
		select_ConnectIEs_RUA_criticality_type,
		{ &asn_OER_memb_RUA_criticality_constr_3, &asn_PER_memb_RUA_criticality_constr_3,  memb_RUA_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectIEs, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RUA_value_4,
		select_ConnectIEs_RUA_value_type,
		{ &asn_OER_memb_RUA_value_constr_4, &asn_PER_memb_RUA_value_constr_4,  memb_RUA_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ConnectIEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_ConnectIEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_RUA_ConnectIEs_specs_1 = {
	sizeof(struct RUA_ConnectIEs),
	offsetof(struct RUA_ConnectIEs, _asn_ctx),
	asn_MAP_RUA_ConnectIEs_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ConnectIEs = {
	"ConnectIEs",
	"ConnectIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RUA_ConnectIEs_tags_1,
	sizeof(asn_DEF_RUA_ConnectIEs_tags_1)
		/sizeof(asn_DEF_RUA_ConnectIEs_tags_1[0]), /* 1 */
	asn_DEF_RUA_ConnectIEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RUA_ConnectIEs_tags_1)
		/sizeof(asn_DEF_RUA_ConnectIEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RUA_ConnectIEs_1,
	3,	/* Elements count */
	&asn_SPC_RUA_ConnectIEs_specs_1	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RUA_value_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs__value, choice.CN_DomainIndicator),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_RUA_CN_DomainIndicator,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CN-DomainIndicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs__value, choice.Context_ID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_RUA_Context_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Context-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs__value, choice.RANAP_Message),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RUA_RANAP_Message,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANAP-Message"
		},
};
static const unsigned asn_MAP_RUA_value_to_canonical_8[] = { 1, 2, 0 };
static const unsigned asn_MAP_RUA_value_from_canonical_8[] = { 2, 0, 1 };
static const asn_TYPE_tag2member_t asn_MAP_RUA_value_tag2el_8[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* Context-ID */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* RANAP-Message */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 } /* CN-DomainIndicator */
};
static asn_CHOICE_specifics_t asn_SPC_RUA_value_specs_8 = {
	sizeof(struct RUA_DirectTransferIEs__value),
	offsetof(struct RUA_DirectTransferIEs__value, _asn_ctx),
	offsetof(struct RUA_DirectTransferIEs__value, present),
	sizeof(((struct RUA_DirectTransferIEs__value *)0)->present),
	asn_MAP_RUA_value_tag2el_8,
	3,	/* Count of tags in the map */
	asn_MAP_RUA_value_to_canonical_8,
	asn_MAP_RUA_value_from_canonical_8,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RUA_value_8 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_RUA_value_8,
	3,	/* Elements count */
	&asn_SPC_RUA_value_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_DirectTransferIEs_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_ProtocolIE_ID,
		0,
		{ &asn_OER_memb_RUA_id_constr_6, &asn_PER_memb_RUA_id_constr_6,  memb_RUA_id_constraint_5 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_Criticality,
		select_DirectTransferIEs_RUA_criticality_type,
		{ &asn_OER_memb_RUA_criticality_constr_7, &asn_PER_memb_RUA_criticality_constr_7,  memb_RUA_criticality_constraint_5 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct RUA_DirectTransferIEs, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RUA_value_8,
		select_DirectTransferIEs_RUA_value_type,
		{ &asn_OER_memb_RUA_value_constr_8, &asn_PER_memb_RUA_value_constr_8,  memb_RUA_value_constraint_5 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_DirectTransferIEs_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_DirectTransferIEs_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_RUA_DirectTransferIEs_specs_5 = {
	sizeof(struct RUA_DirectTransferIEs),
	offsetof(struct RUA_DirectTransferIEs, _asn_ctx),
	asn_MAP_RUA_DirectTransferIEs_tag2el_5,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RUA_DirectTransferIEs = {
	"DirectTransferIEs",
	"DirectTransferIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RUA_DirectTransferIEs_tags_5,
	sizeof(asn_DEF_RUA_DirectTransferIEs_tags_5)
		/sizeof(asn_DEF_RUA_DirectTransferIEs_tags_5[0]), /* 1 */
	asn_DEF_RUA_DirectTransferIEs_tags_5,	/* Same as above */
	sizeof(asn_DEF_RUA_DirectTransferIEs_tags_5)
		/sizeof(asn_DEF_RUA_DirectTransferIEs_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RUA_DirectTransferIEs_5,
	3,	/* Elements count */
	&asn_SPC_RUA_DirectTransferIEs_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RUA_value_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs__value, choice.CN_DomainIndicator),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_RUA_CN_DomainIndicator,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CN-DomainIndicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs__value, choice.Context_ID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_RUA_Context_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Context-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs__value, choice.Cause),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_RUA_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs__value, choice.RANAP_Message),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RUA_RANAP_Message,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANAP-Message"
		},
};
static const unsigned asn_MAP_RUA_value_to_canonical_12[] = { 1, 3, 0, 2 };
static const unsigned asn_MAP_RUA_value_from_canonical_12[] = { 2, 0, 3, 1 };
static const asn_TYPE_tag2member_t asn_MAP_RUA_value_tag2el_12[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* Context-ID */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* RANAP-Message */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 }, /* CN-DomainIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* radioNetwork */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* transport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* protocol */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* misc */
};
static asn_CHOICE_specifics_t asn_SPC_RUA_value_specs_12 = {
	sizeof(struct RUA_DisconnectIEs__value),
	offsetof(struct RUA_DisconnectIEs__value, _asn_ctx),
	offsetof(struct RUA_DisconnectIEs__value, present),
	sizeof(((struct RUA_DisconnectIEs__value *)0)->present),
	asn_MAP_RUA_value_tag2el_12,
	7,	/* Count of tags in the map */
	asn_MAP_RUA_value_to_canonical_12,
	asn_MAP_RUA_value_from_canonical_12,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RUA_value_12 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_RUA_value_12,
	4,	/* Elements count */
	&asn_SPC_RUA_value_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_DisconnectIEs_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_ProtocolIE_ID,
		0,
		{ &asn_OER_memb_RUA_id_constr_10, &asn_PER_memb_RUA_id_constr_10,  memb_RUA_id_constraint_9 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_Criticality,
		select_DisconnectIEs_RUA_criticality_type,
		{ &asn_OER_memb_RUA_criticality_constr_11, &asn_PER_memb_RUA_criticality_constr_11,  memb_RUA_criticality_constraint_9 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct RUA_DisconnectIEs, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RUA_value_12,
		select_DisconnectIEs_RUA_value_type,
		{ &asn_OER_memb_RUA_value_constr_12, &asn_PER_memb_RUA_value_constr_12,  memb_RUA_value_constraint_9 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_DisconnectIEs_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_DisconnectIEs_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_RUA_DisconnectIEs_specs_9 = {
	sizeof(struct RUA_DisconnectIEs),
	offsetof(struct RUA_DisconnectIEs, _asn_ctx),
	asn_MAP_RUA_DisconnectIEs_tag2el_9,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RUA_DisconnectIEs = {
	"DisconnectIEs",
	"DisconnectIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RUA_DisconnectIEs_tags_9,
	sizeof(asn_DEF_RUA_DisconnectIEs_tags_9)
		/sizeof(asn_DEF_RUA_DisconnectIEs_tags_9[0]), /* 1 */
	asn_DEF_RUA_DisconnectIEs_tags_9,	/* Same as above */
	sizeof(asn_DEF_RUA_DisconnectIEs_tags_9)
		/sizeof(asn_DEF_RUA_DisconnectIEs_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RUA_DisconnectIEs_9,
	3,	/* Elements count */
	&asn_SPC_RUA_DisconnectIEs_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RUA_value_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectionlessTransferIEs__value, choice.RANAP_Message),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RUA_RANAP_Message,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RANAP-Message"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_value_tag2el_16[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 } /* RANAP-Message */
};
static asn_CHOICE_specifics_t asn_SPC_RUA_value_specs_16 = {
	sizeof(struct RUA_ConnectionlessTransferIEs__value),
	offsetof(struct RUA_ConnectionlessTransferIEs__value, _asn_ctx),
	offsetof(struct RUA_ConnectionlessTransferIEs__value, present),
	sizeof(((struct RUA_ConnectionlessTransferIEs__value *)0)->present),
	asn_MAP_RUA_value_tag2el_16,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RUA_value_16 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_RUA_value_16,
	1,	/* Elements count */
	&asn_SPC_RUA_value_specs_16	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ConnectionlessTransferIEs_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectionlessTransferIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_ProtocolIE_ID,
		0,
		{ &asn_OER_memb_RUA_id_constr_14, &asn_PER_memb_RUA_id_constr_14,  memb_RUA_id_constraint_13 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectionlessTransferIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_Criticality,
		select_ConnectionlessTransferIEs_RUA_criticality_type,
		{ &asn_OER_memb_RUA_criticality_constr_15, &asn_PER_memb_RUA_criticality_constr_15,  memb_RUA_criticality_constraint_13 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct RUA_ConnectionlessTransferIEs, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RUA_value_16,
		select_ConnectionlessTransferIEs_RUA_value_type,
		{ &asn_OER_memb_RUA_value_constr_16, &asn_PER_memb_RUA_value_constr_16,  memb_RUA_value_constraint_13 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ConnectionlessTransferIEs_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_ConnectionlessTransferIEs_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_RUA_ConnectionlessTransferIEs_specs_13 = {
	sizeof(struct RUA_ConnectionlessTransferIEs),
	offsetof(struct RUA_ConnectionlessTransferIEs, _asn_ctx),
	asn_MAP_RUA_ConnectionlessTransferIEs_tag2el_13,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ConnectionlessTransferIEs = {
	"ConnectionlessTransferIEs",
	"ConnectionlessTransferIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RUA_ConnectionlessTransferIEs_tags_13,
	sizeof(asn_DEF_RUA_ConnectionlessTransferIEs_tags_13)
		/sizeof(asn_DEF_RUA_ConnectionlessTransferIEs_tags_13[0]), /* 1 */
	asn_DEF_RUA_ConnectionlessTransferIEs_tags_13,	/* Same as above */
	sizeof(asn_DEF_RUA_ConnectionlessTransferIEs_tags_13)
		/sizeof(asn_DEF_RUA_ConnectionlessTransferIEs_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RUA_ConnectionlessTransferIEs_13,
	3,	/* Elements count */
	&asn_SPC_RUA_ConnectionlessTransferIEs_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RUA_value_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ErrorIndicationIEs__value, choice.Cause),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_RUA_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ErrorIndicationIEs__value, choice.CriticalityDiagnostics),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_CriticalityDiagnostics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CriticalityDiagnostics"
		},
};
static const unsigned asn_MAP_RUA_value_to_canonical_20[] = { 1, 0 };
static const unsigned asn_MAP_RUA_value_from_canonical_20[] = { 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_RUA_value_tag2el_20[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* CriticalityDiagnostics */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioNetwork */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* transport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* protocol */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* misc */
};
static asn_CHOICE_specifics_t asn_SPC_RUA_value_specs_20 = {
	sizeof(struct RUA_ErrorIndicationIEs__value),
	offsetof(struct RUA_ErrorIndicationIEs__value, _asn_ctx),
	offsetof(struct RUA_ErrorIndicationIEs__value, present),
	sizeof(((struct RUA_ErrorIndicationIEs__value *)0)->present),
	asn_MAP_RUA_value_tag2el_20,
	5,	/* Count of tags in the map */
	asn_MAP_RUA_value_to_canonical_20,
	asn_MAP_RUA_value_from_canonical_20,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RUA_value_20 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_RUA_value_20,
	2,	/* Elements count */
	&asn_SPC_RUA_value_specs_20	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ErrorIndicationIEs_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ErrorIndicationIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_ProtocolIE_ID,
		0,
		{ &asn_OER_memb_RUA_id_constr_18, &asn_PER_memb_RUA_id_constr_18,  memb_RUA_id_constraint_17 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RUA_ErrorIndicationIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RUA_Criticality,
		select_ErrorIndicationIEs_RUA_criticality_type,
		{ &asn_OER_memb_RUA_criticality_constr_19, &asn_PER_memb_RUA_criticality_constr_19,  memb_RUA_criticality_constraint_17 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct RUA_ErrorIndicationIEs, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RUA_value_20,
		select_ErrorIndicationIEs_RUA_value_type,
		{ &asn_OER_memb_RUA_value_constr_20, &asn_PER_memb_RUA_value_constr_20,  memb_RUA_value_constraint_17 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ErrorIndicationIEs_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RUA_ErrorIndicationIEs_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_RUA_ErrorIndicationIEs_specs_17 = {
	sizeof(struct RUA_ErrorIndicationIEs),
	offsetof(struct RUA_ErrorIndicationIEs, _asn_ctx),
	asn_MAP_RUA_ErrorIndicationIEs_tag2el_17,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ErrorIndicationIEs = {
	"ErrorIndicationIEs",
	"ErrorIndicationIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RUA_ErrorIndicationIEs_tags_17,
	sizeof(asn_DEF_RUA_ErrorIndicationIEs_tags_17)
		/sizeof(asn_DEF_RUA_ErrorIndicationIEs_tags_17[0]), /* 1 */
	asn_DEF_RUA_ErrorIndicationIEs_tags_17,	/* Same as above */
	sizeof(asn_DEF_RUA_ErrorIndicationIEs_tags_17)
		/sizeof(asn_DEF_RUA_ErrorIndicationIEs_tags_17[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RUA_ErrorIndicationIEs_17,
	3,	/* Elements count */
	&asn_SPC_RUA_ErrorIndicationIEs_specs_17	/* Additional specs */
};

