/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-Containers"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/rua/RUA_ProtocolIE-Container.h>

#include <osmocom/rua/RUA_ProtocolIE-Field.h>
static asn_oer_constraints_t asn_OER_type_RUA_ProtocolIE_Container_769P0_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RUA_ProtocolIE_Container_769P1_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RUA_ProtocolIE_Container_769P2_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RUA_ProtocolIE_Container_769P3_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RUA_ProtocolIE_Container_769P4_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_ConnectIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P0_specs_1 = {
	sizeof(struct RUA_ProtocolIE_Container_769P0),
	offsetof(struct RUA_ProtocolIE_Container_769P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1,
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1[0]), /* 1 */
	asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P0_tags_1[0]), /* 1 */
	{ &asn_OER_type_RUA_ProtocolIE_Container_769P0_constr_1, &asn_PER_type_RUA_ProtocolIE_Container_769P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_RUA_ProtocolIE_Container_769P0_1,
	1,	/* Single element */
	&asn_SPC_RUA_ProtocolIE_Container_769P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_DirectTransferIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P1_specs_3 = {
	sizeof(struct RUA_ProtocolIE_Container_769P1),
	offsetof(struct RUA_ProtocolIE_Container_769P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P1 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3,
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3[0]), /* 1 */
	asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P1_tags_3[0]), /* 1 */
	{ &asn_OER_type_RUA_ProtocolIE_Container_769P1_constr_3, &asn_PER_type_RUA_ProtocolIE_Container_769P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_RUA_ProtocolIE_Container_769P1_3,
	1,	/* Single element */
	&asn_SPC_RUA_ProtocolIE_Container_769P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_DisconnectIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P2_specs_5 = {
	sizeof(struct RUA_ProtocolIE_Container_769P2),
	offsetof(struct RUA_ProtocolIE_Container_769P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P2 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5,
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5[0]), /* 1 */
	asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P2_tags_5[0]), /* 1 */
	{ &asn_OER_type_RUA_ProtocolIE_Container_769P2_constr_5, &asn_PER_type_RUA_ProtocolIE_Container_769P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_RUA_ProtocolIE_Container_769P2_5,
	1,	/* Single element */
	&asn_SPC_RUA_ProtocolIE_Container_769P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_ConnectionlessTransferIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P3_specs_7 = {
	sizeof(struct RUA_ProtocolIE_Container_769P3),
	offsetof(struct RUA_ProtocolIE_Container_769P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P3 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7,
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7[0]), /* 1 */
	asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P3_tags_7[0]), /* 1 */
	{ &asn_OER_type_RUA_ProtocolIE_Container_769P3_constr_7, &asn_PER_type_RUA_ProtocolIE_Container_769P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_RUA_ProtocolIE_Container_769P3_7,
	1,	/* Single element */
	&asn_SPC_RUA_ProtocolIE_Container_769P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RUA_ErrorIndicationIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P4_specs_9 = {
	sizeof(struct RUA_ProtocolIE_Container_769P4),
	offsetof(struct RUA_ProtocolIE_Container_769P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P4 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9,
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9[0]), /* 1 */
	asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9)
		/sizeof(asn_DEF_RUA_ProtocolIE_Container_769P4_tags_9[0]), /* 1 */
	{ &asn_OER_type_RUA_ProtocolIE_Container_769P4_constr_9, &asn_PER_type_RUA_ProtocolIE_Container_769P4_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_RUA_ProtocolIE_Container_769P4_9,
	1,	/* Single element */
	&asn_SPC_RUA_ProtocolIE_Container_769P4_specs_9	/* Additional specs */
};

