/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/Access-stratum-release-indicator.h>

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Access_stratum_release_indicator_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Access_stratum_release_indicator_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Access_stratum_release_indicator_value2enum_1[] = {
	{ 0,	3,	"r99" },
	{ 1,	5,	"rel-4" },
	{ 2,	5,	"rel-5" },
	{ 3,	5,	"rel-6" },
	{ 4,	5,	"rel-7" },
	{ 5,	16,	"rel-8-and-beyond" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_Access_stratum_release_indicator_enum2value_1[] = {
	0,	/* r99(0) */
	1,	/* rel-4(1) */
	2,	/* rel-5(2) */
	3,	/* rel-6(3) */
	4,	/* rel-7(4) */
	5	/* rel-8-and-beyond(5) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_Access_stratum_release_indicator_specs_1 = {
	asn_MAP_Access_stratum_release_indicator_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Access_stratum_release_indicator_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Access_stratum_release_indicator_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Access_stratum_release_indicator = {
	"Access-stratum-release-indicator",
	"Access-stratum-release-indicator",
	&asn_OP_NativeEnumerated,
	asn_DEF_Access_stratum_release_indicator_tags_1,
	sizeof(asn_DEF_Access_stratum_release_indicator_tags_1)
		/sizeof(asn_DEF_Access_stratum_release_indicator_tags_1[0]), /* 1 */
	asn_DEF_Access_stratum_release_indicator_tags_1,	/* Same as above */
	sizeof(asn_DEF_Access_stratum_release_indicator_tags_1)
		/sizeof(asn_DEF_Access_stratum_release_indicator_tags_1[0]), /* 1 */
	{ &asn_OER_type_Access_stratum_release_indicator_constr_1, &asn_PER_type_Access_stratum_release_indicator_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Access_stratum_release_indicator_specs_1	/* Additional specs */
};

