/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/IMSIESN.h>

asn_TYPE_member_t asn_MBR_IMSIESN_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IMSIESN, iMSIDS41),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSIDS41,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMSIDS41"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IMSIESN, eSN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ESN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eSN"
		},
};
static const ber_tlv_tag_t asn_DEF_IMSIESN_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IMSIESN_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iMSIDS41 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eSN */
};
asn_SEQUENCE_specifics_t asn_SPC_IMSIESN_specs_1 = {
	sizeof(struct IMSIESN),
	offsetof(struct IMSIESN, _asn_ctx),
	asn_MAP_IMSIESN_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IMSIESN = {
	"IMSIESN",
	"IMSIESN",
	&asn_OP_SEQUENCE,
	asn_DEF_IMSIESN_tags_1,
	sizeof(asn_DEF_IMSIESN_tags_1)
		/sizeof(asn_DEF_IMSIESN_tags_1[0]), /* 1 */
	asn_DEF_IMSIESN_tags_1,	/* Same as above */
	sizeof(asn_DEF_IMSIESN_tags_1)
		/sizeof(asn_DEF_IMSIESN_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IMSIESN_1,
	2,	/* Elements count */
	&asn_SPC_IMSIESN_specs_1	/* Additional specs */
};

