/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/IP-Address.h>

#include <osmocom/hnbap/ProtocolExtensionContainer.h>
static asn_oer_constraints_t asn_OER_type_ipaddress_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ipaddress_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ipaddress_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IP_Address__ipaddress, choice.ipv4info),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ipv4Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipv4info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IP_Address__ipaddress, choice.ipv6info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ipv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipv6info"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ipaddress_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ipv4info */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ipv6info */
};
static asn_CHOICE_specifics_t asn_SPC_ipaddress_specs_2 = {
	sizeof(struct IP_Address__ipaddress),
	offsetof(struct IP_Address__ipaddress, _asn_ctx),
	offsetof(struct IP_Address__ipaddress, present),
	sizeof(((struct IP_Address__ipaddress *)0)->present),
	asn_MAP_ipaddress_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipaddress_2 = {
	"ipaddress",
	"ipaddress",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ipaddress_constr_2, &asn_PER_type_ipaddress_constr_2, CHOICE_constraint },
	asn_MBR_ipaddress_2,
	2,	/* Elements count */
	&asn_SPC_ipaddress_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_IP_Address_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IP_Address, ipaddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ipaddress_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipaddress"
		},
	{ ATF_POINTER, 1, offsetof(struct IP_Address, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_1637P29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_IP_Address_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_IP_Address_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IP_Address_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ipaddress */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_IP_Address_specs_1 = {
	sizeof(struct IP_Address),
	offsetof(struct IP_Address, _asn_ctx),
	asn_MAP_IP_Address_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_IP_Address_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IP_Address = {
	"IP-Address",
	"IP-Address",
	&asn_OP_SEQUENCE,
	asn_DEF_IP_Address_tags_1,
	sizeof(asn_DEF_IP_Address_tags_1)
		/sizeof(asn_DEF_IP_Address_tags_1[0]), /* 1 */
	asn_DEF_IP_Address_tags_1,	/* Same as above */
	sizeof(asn_DEF_IP_Address_tags_1)
		/sizeof(asn_DEF_IP_Address_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IP_Address_1,
	2,	/* Elements count */
	&asn_SPC_IP_Address_specs_1	/* Additional specs */
};

