/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-Containers"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/ProtocolExtensionContainer.h>

#include <osmocom/hnbap/ProtocolExtensionField.h>
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P0_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P1_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P2_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P3_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P4_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P5_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P6_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P7_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P8_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P9_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P9_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P10_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P10_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P11_constr_23 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P11_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P12_constr_25 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P12_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P13_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P13_constr_27 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P14_constr_29 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P14_constr_29 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P15_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P15_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P16_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P16_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P17_constr_35 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P17_constr_35 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P18_constr_37 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P18_constr_37 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P19_constr_39 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P19_constr_39 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P20_constr_41 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P20_constr_41 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P21_constr_43 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P21_constr_43 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P22_constr_45 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P22_constr_45 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P23_constr_47 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P23_constr_47 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P24_constr_49 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P24_constr_49 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P25_constr_51 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P25_constr_51 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P26_constr_53 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P26_constr_53 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P27_constr_55 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P27_constr_55 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P28_constr_57 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P28_constr_57 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P29_constr_59 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P29_constr_59 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P30_constr_61 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P30_constr_61 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P31_constr_63 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P31_constr_63 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P32_constr_65 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P32_constr_65 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P33_constr_67 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P33_constr_67 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P34_constr_69 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P34_constr_69 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P35_constr_71 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P35_constr_71 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolExtensionContainer_1637P36_constr_73 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_1637P36_constr_73 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBRegisterRequestExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P0_specs_1 = {
	sizeof(struct ProtocolExtensionContainer_1637P0),
	offsetof(struct ProtocolExtensionContainer_1637P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P0 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P0_tags_1,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P0_tags_1)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P0_tags_1)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P0_tags_1[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P0_constr_1, &asn_PER_type_ProtocolExtensionContainer_1637P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P0_1,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBRegisterResponseExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P1_specs_3 = {
	sizeof(struct ProtocolExtensionContainer_1637P1),
	offsetof(struct ProtocolExtensionContainer_1637P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P1 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P1_tags_3,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P1_tags_3)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P1_tags_3[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P1_tags_3)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P1_tags_3[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P1_constr_3, &asn_PER_type_ProtocolExtensionContainer_1637P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P1_3,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBRegisterRejectExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P2_specs_5 = {
	sizeof(struct ProtocolExtensionContainer_1637P2),
	offsetof(struct ProtocolExtensionContainer_1637P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P2 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P2_tags_5,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P2_tags_5)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P2_tags_5[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P2_tags_5)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P2_tags_5[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P2_constr_5, &asn_PER_type_ProtocolExtensionContainer_1637P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P2_5,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBDe_RegisterExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P3_specs_7 = {
	sizeof(struct ProtocolExtensionContainer_1637P3),
	offsetof(struct ProtocolExtensionContainer_1637P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P3 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P3_tags_7,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P3_tags_7)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P3_tags_7[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P3_tags_7)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P3_tags_7[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P3_constr_7, &asn_PER_type_ProtocolExtensionContainer_1637P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P3_7,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UERegisterRequestExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P4_specs_9 = {
	sizeof(struct ProtocolExtensionContainer_1637P4),
	offsetof(struct ProtocolExtensionContainer_1637P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P4 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P4_tags_9,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P4_tags_9)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P4_tags_9[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P4_tags_9)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P4_tags_9[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P4_constr_9, &asn_PER_type_ProtocolExtensionContainer_1637P4_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P4_9,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UERegisterAcceptExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P5_specs_11 = {
	sizeof(struct ProtocolExtensionContainer_1637P5),
	offsetof(struct ProtocolExtensionContainer_1637P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P5 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P5_tags_11,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P5_tags_11)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P5_tags_11[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P5_tags_11)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P5_tags_11[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P5_constr_11, &asn_PER_type_ProtocolExtensionContainer_1637P5_constr_11, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P5_11,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UERegisterRejectExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P6_specs_13 = {
	sizeof(struct ProtocolExtensionContainer_1637P6),
	offsetof(struct ProtocolExtensionContainer_1637P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P6 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P6_tags_13,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P6_tags_13)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P6_tags_13[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P6_tags_13)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P6_tags_13[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P6_constr_13, &asn_PER_type_ProtocolExtensionContainer_1637P6_constr_13, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P6_13,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UEDe_RegisterExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P7_specs_15 = {
	sizeof(struct ProtocolExtensionContainer_1637P7),
	offsetof(struct ProtocolExtensionContainer_1637P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P7 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P7_tags_15,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P7_tags_15)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P7_tags_15[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P7_tags_15)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P7_tags_15[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P7_constr_15, &asn_PER_type_ProtocolExtensionContainer_1637P7_constr_15, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P7_15,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CSGMembershipUpdateExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P8_specs_17 = {
	sizeof(struct ProtocolExtensionContainer_1637P8),
	offsetof(struct ProtocolExtensionContainer_1637P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P8 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P8_tags_17,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P8_tags_17)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P8_tags_17[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P8_tags_17)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P8_tags_17[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P8_constr_17, &asn_PER_type_ProtocolExtensionContainer_1637P8_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P8_17,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P8_specs_17	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P9_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TNLUpdateExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P9_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P9_specs_19 = {
	sizeof(struct ProtocolExtensionContainer_1637P9),
	offsetof(struct ProtocolExtensionContainer_1637P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P9 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P9_tags_19,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P9_tags_19)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P9_tags_19[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P9_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P9_tags_19)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P9_tags_19[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P9_constr_19, &asn_PER_type_ProtocolExtensionContainer_1637P9_constr_19, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P9_19,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P9_specs_19	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P10_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TNLUpdateResponseExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P10_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P10_specs_21 = {
	sizeof(struct ProtocolExtensionContainer_1637P10),
	offsetof(struct ProtocolExtensionContainer_1637P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P10 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P10_tags_21,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P10_tags_21)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P10_tags_21[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P10_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P10_tags_21)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P10_tags_21[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P10_constr_21, &asn_PER_type_ProtocolExtensionContainer_1637P10_constr_21, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P10_21,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P10_specs_21	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P11_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TNLUpdateFailureExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P11_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P11_specs_23 = {
	sizeof(struct ProtocolExtensionContainer_1637P11),
	offsetof(struct ProtocolExtensionContainer_1637P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P11 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P11_tags_23,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P11_tags_23)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P11_tags_23[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P11_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P11_tags_23)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P11_tags_23[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P11_constr_23, &asn_PER_type_ProtocolExtensionContainer_1637P11_constr_23, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P11_23,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P11_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P12_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBConfigTransferRequestExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P12_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P12_specs_25 = {
	sizeof(struct ProtocolExtensionContainer_1637P12),
	offsetof(struct ProtocolExtensionContainer_1637P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P12 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P12_tags_25,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P12_tags_25)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P12_tags_25[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P12_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P12_tags_25)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P12_tags_25[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P12_constr_25, &asn_PER_type_ProtocolExtensionContainer_1637P12_constr_25, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P12_25,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P12_specs_25	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P13_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBConfigTransferResponseExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P13_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P13_specs_27 = {
	sizeof(struct ProtocolExtensionContainer_1637P13),
	offsetof(struct ProtocolExtensionContainer_1637P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P13 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P13_tags_27,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P13_tags_27)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P13_tags_27[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P13_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P13_tags_27)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P13_tags_27[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P13_constr_27, &asn_PER_type_ProtocolExtensionContainer_1637P13_constr_27, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P13_27,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P13_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P14_29[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RelocationCompleteExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P14_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P14_specs_29 = {
	sizeof(struct ProtocolExtensionContainer_1637P14),
	offsetof(struct ProtocolExtensionContainer_1637P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P14 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P14_tags_29,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P14_tags_29)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P14_tags_29[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P14_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P14_tags_29)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P14_tags_29[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P14_constr_29, &asn_PER_type_ProtocolExtensionContainer_1637P14_constr_29, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P14_29,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P14_specs_29	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P15_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ErrorIndicationExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P15_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P15_specs_31 = {
	sizeof(struct ProtocolExtensionContainer_1637P15),
	offsetof(struct ProtocolExtensionContainer_1637P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P15 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P15_tags_31,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P15_tags_31)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P15_tags_31[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P15_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P15_tags_31)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P15_tags_31[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P15_constr_31, &asn_PER_type_ProtocolExtensionContainer_1637P15_constr_31, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P15_31,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P15_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P16_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_U_RNTIQueryRequestExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P16_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P16_specs_33 = {
	sizeof(struct ProtocolExtensionContainer_1637P16),
	offsetof(struct ProtocolExtensionContainer_1637P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P16 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P16_tags_33,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P16_tags_33)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P16_tags_33[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P16_tags_33,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P16_tags_33)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P16_tags_33[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P16_constr_33, &asn_PER_type_ProtocolExtensionContainer_1637P16_constr_33, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P16_33,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P16_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P17_35[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_U_RNTIQueryResponseExtensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P17_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P17_specs_35 = {
	sizeof(struct ProtocolExtensionContainer_1637P17),
	offsetof(struct ProtocolExtensionContainer_1637P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P17 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P17_tags_35,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P17_tags_35)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P17_tags_35[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P17_tags_35,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P17_tags_35)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P17_tags_35[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P17_constr_35, &asn_PER_type_ProtocolExtensionContainer_1637P17_constr_35, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P17_35,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P17_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P18_37[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CriticalityDiagnostics_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P18_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P18_specs_37 = {
	sizeof(struct ProtocolExtensionContainer_1637P18),
	offsetof(struct ProtocolExtensionContainer_1637P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P18 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P18_tags_37,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P18_tags_37)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P18_tags_37[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P18_tags_37,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P18_tags_37)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P18_tags_37[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P18_constr_37, &asn_PER_type_ProtocolExtensionContainer_1637P18_constr_37, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P18_37,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P18_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P19_39[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CriticalityDiagnostics_IE_List_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P19_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P19_specs_39 = {
	sizeof(struct ProtocolExtensionContainer_1637P19),
	offsetof(struct ProtocolExtensionContainer_1637P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P19 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P19_tags_39,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P19_tags_39)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P19_tags_39[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P19_tags_39,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P19_tags_39)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P19_tags_39[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P19_constr_39, &asn_PER_type_ProtocolExtensionContainer_1637P19_constr_39, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P19_39,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P19_specs_39	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P20_41[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CGI_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P20_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P20_specs_41 = {
	sizeof(struct ProtocolExtensionContainer_1637P20),
	offsetof(struct ProtocolExtensionContainer_1637P20, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P20 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P20_tags_41,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P20_tags_41)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P20_tags_41[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P20_tags_41,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P20_tags_41)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P20_tags_41[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P20_constr_41, &asn_PER_type_ProtocolExtensionContainer_1637P20_constr_41, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P20_41,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P20_specs_41	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P21_43[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeographicLocation_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P21_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P21_specs_43 = {
	sizeof(struct ProtocolExtensionContainer_1637P21),
	offsetof(struct ProtocolExtensionContainer_1637P21, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P21 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P21_tags_43,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P21_tags_43)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P21_tags_43[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P21_tags_43,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P21_tags_43)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P21_tags_43[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P21_constr_43, &asn_PER_type_ProtocolExtensionContainer_1637P21_constr_43, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P21_43,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P21_specs_43	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P22_45[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeographicalCoordinates_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P22_tags_45[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P22_specs_45 = {
	sizeof(struct ProtocolExtensionContainer_1637P22),
	offsetof(struct ProtocolExtensionContainer_1637P22, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P22 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P22_tags_45,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P22_tags_45)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P22_tags_45[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P22_tags_45,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P22_tags_45)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P22_tags_45[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P22_constr_45, &asn_PER_type_ProtocolExtensionContainer_1637P22_constr_45, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P22_45,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P22_specs_45	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P23_47[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNB_Cell_Identifier_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P23_tags_47[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P23_specs_47 = {
	sizeof(struct ProtocolExtensionContainer_1637P23),
	offsetof(struct ProtocolExtensionContainer_1637P23, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P23 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P23_tags_47,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P23_tags_47)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P23_tags_47[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P23_tags_47,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P23_tags_47)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P23_tags_47[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P23_constr_47, &asn_PER_type_ProtocolExtensionContainer_1637P23_constr_47, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P23_47,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P23_specs_47	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P24_49[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBConfigInfo_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P24_tags_49[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P24_specs_49 = {
	sizeof(struct ProtocolExtensionContainer_1637P24),
	offsetof(struct ProtocolExtensionContainer_1637P24, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P24 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P24_tags_49,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P24_tags_49)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P24_tags_49[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P24_tags_49,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P24_tags_49)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P24_tags_49[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P24_constr_49, &asn_PER_type_ProtocolExtensionContainer_1637P24_constr_49, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P24_49,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P24_specs_49	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P25_51[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBConfigurationInformationProvided_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P25_tags_51[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P25_specs_51 = {
	sizeof(struct ProtocolExtensionContainer_1637P25),
	offsetof(struct ProtocolExtensionContainer_1637P25, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P25 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P25_tags_51,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P25_tags_51)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P25_tags_51[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P25_tags_51,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P25_tags_51)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P25_tags_51[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P25_constr_51, &asn_PER_type_ProtocolExtensionContainer_1637P25_constr_51, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P25_51,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P25_specs_51	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P26_53[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNBConfigurationInformationMissing_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P26_tags_53[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P26_specs_53 = {
	sizeof(struct ProtocolExtensionContainer_1637P26),
	offsetof(struct ProtocolExtensionContainer_1637P26, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P26 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P26_tags_53,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P26_tags_53)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P26_tags_53[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P26_tags_53,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P26_tags_53)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P26_tags_53[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P26_constr_53, &asn_PER_type_ProtocolExtensionContainer_1637P26_constr_53, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P26_53,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P26_specs_53	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P27_55[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNB_Location_Information_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P27_tags_55[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P27_specs_55 = {
	sizeof(struct ProtocolExtensionContainer_1637P27),
	offsetof(struct ProtocolExtensionContainer_1637P27, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P27 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P27_tags_55,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P27_tags_55)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P27_tags_55[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P27_tags_55,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P27_tags_55)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P27_tags_55[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P27_constr_55, &asn_PER_type_ProtocolExtensionContainer_1637P27_constr_55, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P27_55,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P27_specs_55	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P28_57[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HNB_Identity_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P28_tags_57[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P28_specs_57 = {
	sizeof(struct ProtocolExtensionContainer_1637P28),
	offsetof(struct ProtocolExtensionContainer_1637P28, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P28 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P28_tags_57,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P28_tags_57)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P28_tags_57[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P28_tags_57,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P28_tags_57)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P28_tags_57[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P28_constr_57, &asn_PER_type_ProtocolExtensionContainer_1637P28_constr_57, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P28_57,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P28_specs_57	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P29_59[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IP_Address_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P29_tags_59[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P29_specs_59 = {
	sizeof(struct ProtocolExtensionContainer_1637P29),
	offsetof(struct ProtocolExtensionContainer_1637P29, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P29 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P29_tags_59,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P29_tags_59)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P29_tags_59[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P29_tags_59,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P29_tags_59)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P29_tags_59[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P29_constr_59, &asn_PER_type_ProtocolExtensionContainer_1637P29_constr_59, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P29_59,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P29_specs_59	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P30_61[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MacroCoverageInformation_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P30_tags_61[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P30_specs_61 = {
	sizeof(struct ProtocolExtensionContainer_1637P30),
	offsetof(struct ProtocolExtensionContainer_1637P30, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P30 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P30_tags_61,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P30_tags_61)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P30_tags_61[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P30_tags_61,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P30_tags_61)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P30_tags_61[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P30_constr_61, &asn_PER_type_ProtocolExtensionContainer_1637P30_constr_61, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P30_61,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P30_specs_61	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P31_63[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NeighbourInfoRequestItem_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P31_tags_63[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P31_specs_63 = {
	sizeof(struct ProtocolExtensionContainer_1637P31),
	offsetof(struct ProtocolExtensionContainer_1637P31, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P31 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P31_tags_63,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P31_tags_63)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P31_tags_63[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P31_tags_63,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P31_tags_63)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P31_tags_63[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P31_constr_63, &asn_PER_type_ProtocolExtensionContainer_1637P31_constr_63, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P31_63,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P31_specs_63	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P32_65[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RABListItem_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P32_tags_65[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P32_specs_65 = {
	sizeof(struct ProtocolExtensionContainer_1637P32),
	offsetof(struct ProtocolExtensionContainer_1637P32, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P32 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P32_tags_65,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P32_tags_65)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P32_tags_65[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P32_tags_65,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P32_tags_65)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P32_tags_65[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P32_constr_65, &asn_PER_type_ProtocolExtensionContainer_1637P32_constr_65, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P32_65,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P32_specs_65	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P33_67[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TransportInfo_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P33_tags_67[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P33_specs_67 = {
	sizeof(struct ProtocolExtensionContainer_1637P33),
	offsetof(struct ProtocolExtensionContainer_1637P33, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P33 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P33_tags_67,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P33_tags_67)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P33_tags_67[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P33_tags_67,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P33_tags_67)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P33_tags_67[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P33_constr_67, &asn_PER_type_ProtocolExtensionContainer_1637P33_constr_67, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P33_67,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P33_specs_67	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P34_69[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Tunnel_Information_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P34_tags_69[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P34_specs_69 = {
	sizeof(struct ProtocolExtensionContainer_1637P34),
	offsetof(struct ProtocolExtensionContainer_1637P34, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P34 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P34_tags_69,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P34_tags_69)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P34_tags_69[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P34_tags_69,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P34_tags_69)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P34_tags_69[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P34_constr_69, &asn_PER_type_ProtocolExtensionContainer_1637P34_constr_69, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P34_69,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P34_specs_69	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P35_71[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UE_Capabilities_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P35_tags_71[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P35_specs_71 = {
	sizeof(struct ProtocolExtensionContainer_1637P35),
	offsetof(struct ProtocolExtensionContainer_1637P35, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P35 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P35_tags_71,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P35_tags_71)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P35_tags_71[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P35_tags_71,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P35_tags_71)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P35_tags_71[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P35_constr_71, &asn_PER_type_ProtocolExtensionContainer_1637P35_constr_71, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P35_71,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P35_specs_71	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_1637P36_73[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UTRANCellID_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolExtensionContainer_1637P36_tags_73[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_1637P36_specs_73 = {
	sizeof(struct ProtocolExtensionContainer_1637P36),
	offsetof(struct ProtocolExtensionContainer_1637P36, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_1637P36 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolExtensionContainer_1637P36_tags_73,
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P36_tags_73)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P36_tags_73[0]), /* 1 */
	asn_DEF_ProtocolExtensionContainer_1637P36_tags_73,	/* Same as above */
	sizeof(asn_DEF_ProtocolExtensionContainer_1637P36_tags_73)
		/sizeof(asn_DEF_ProtocolExtensionContainer_1637P36_tags_73[0]), /* 1 */
	{ &asn_OER_type_ProtocolExtensionContainer_1637P36_constr_73, &asn_PER_type_ProtocolExtensionContainer_1637P36_constr_73, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolExtensionContainer_1637P36_73,
	1,	/* Single element */
	&asn_SPC_ProtocolExtensionContainer_1637P36_specs_73	/* Additional specs */
};

