/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/PTMSIRAI.h>

asn_TYPE_member_t asn_MBR_PTMSIRAI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PTMSIRAI, pTMSI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PTMSI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pTMSI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PTMSIRAI, rAI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rAI"
		},
};
static const ber_tlv_tag_t asn_DEF_PTMSIRAI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PTMSIRAI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pTMSI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rAI */
};
asn_SEQUENCE_specifics_t asn_SPC_PTMSIRAI_specs_1 = {
	sizeof(struct PTMSIRAI),
	offsetof(struct PTMSIRAI, _asn_ctx),
	asn_MAP_PTMSIRAI_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PTMSIRAI = {
	"PTMSIRAI",
	"PTMSIRAI",
	&asn_OP_SEQUENCE,
	asn_DEF_PTMSIRAI_tags_1,
	sizeof(asn_DEF_PTMSIRAI_tags_1)
		/sizeof(asn_DEF_PTMSIRAI_tags_1[0]), /* 1 */
	asn_DEF_PTMSIRAI_tags_1,	/* Same as above */
	sizeof(asn_DEF_PTMSIRAI_tags_1)
		/sizeof(asn_DEF_PTMSIRAI_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PTMSIRAI_1,
	2,	/* Elements count */
	&asn_SPC_PTMSIRAI_specs_1	/* Additional specs */
};

