/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/hnbap-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/hnbap/TransportInfo.h>

#include <osmocom/hnbap/ProtocolExtensionContainer.h>
static asn_oer_constraints_t asn_OER_type_transportAssociation_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_transportAssociation_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_transportAssociation_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TransportInfo__transportAssociation, choice.gtp_TEI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GTP_TEI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gtp-TEI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransportInfo__transportAssociation, choice.bindingID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BindingID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bindingID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_transportAssociation_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gtp-TEI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bindingID */
};
static asn_CHOICE_specifics_t asn_SPC_transportAssociation_specs_3 = {
	sizeof(struct TransportInfo__transportAssociation),
	offsetof(struct TransportInfo__transportAssociation, _asn_ctx),
	offsetof(struct TransportInfo__transportAssociation, present),
	sizeof(((struct TransportInfo__transportAssociation *)0)->present),
	asn_MAP_transportAssociation_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transportAssociation_3 = {
	"transportAssociation",
	"transportAssociation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_transportAssociation_constr_3, &asn_PER_type_transportAssociation_constr_3, CHOICE_constraint },
	asn_MBR_transportAssociation_3,
	2,	/* Elements count */
	&asn_SPC_transportAssociation_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TransportInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TransportInfo, transportLayerAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransportLayerAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transportLayerAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransportInfo, transportAssociation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_transportAssociation_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transportAssociation"
		},
	{ ATF_POINTER, 1, offsetof(struct TransportInfo, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_1637P33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_TransportInfo_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_TransportInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TransportInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transportLayerAddress */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transportAssociation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_TransportInfo_specs_1 = {
	sizeof(struct TransportInfo),
	offsetof(struct TransportInfo, _asn_ctx),
	asn_MAP_TransportInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_TransportInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TransportInfo = {
	"TransportInfo",
	"TransportInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_TransportInfo_tags_1,
	sizeof(asn_DEF_TransportInfo_tags_1)
		/sizeof(asn_DEF_TransportInfo_tags_1[0]), /* 1 */
	asn_DEF_TransportInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransportInfo_tags_1)
		/sizeof(asn_DEF_TransportInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TransportInfo_1,
	3,	/* Elements count */
	&asn_SPC_TransportInfo_specs_1	/* Additional specs */
};

