/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-Containers"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RUA_ProtocolIE_Field_H_
#define	_RUA_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rua/RUA_ProtocolIE-ID.h>
#include <osmocom/rua/RUA_Criticality.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <osmocom/rua/RUA_CN-DomainIndicator.h>
#include <osmocom/rua/RUA_Presence.h>
#include <osmocom/rua/RUA_Context-ID.h>
#include <osmocom/rua/RUA_IntraDomainNasNodeSelector.h>
#include <osmocom/rua/RUA_Establishment-Cause.h>
#include <osmocom/rua/RUA_RANAP-Message.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <osmocom/rua/RUA_Cause.h>
#include <osmocom/rua/RUA_CriticalityDiagnostics.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RUA_ConnectIEs__value_PR {
	RUA_ConnectIEs__value_PR_NOTHING,	/* No components present */
	RUA_ConnectIEs__value_PR_CN_DomainIndicator,
	RUA_ConnectIEs__value_PR_Context_ID,
	RUA_ConnectIEs__value_PR_IntraDomainNasNodeSelector,
	RUA_ConnectIEs__value_PR_Establishment_Cause,
	RUA_ConnectIEs__value_PR_RANAP_Message
} RUA_ConnectIEs__value_PR;
typedef enum RUA_DirectTransferIEs__value_PR {
	RUA_DirectTransferIEs__value_PR_NOTHING,	/* No components present */
	RUA_DirectTransferIEs__value_PR_CN_DomainIndicator,
	RUA_DirectTransferIEs__value_PR_Context_ID,
	RUA_DirectTransferIEs__value_PR_RANAP_Message
} RUA_DirectTransferIEs__value_PR;
typedef enum RUA_DisconnectIEs__value_PR {
	RUA_DisconnectIEs__value_PR_NOTHING,	/* No components present */
	RUA_DisconnectIEs__value_PR_CN_DomainIndicator,
	RUA_DisconnectIEs__value_PR_Context_ID,
	RUA_DisconnectIEs__value_PR_Cause,
	RUA_DisconnectIEs__value_PR_RANAP_Message
} RUA_DisconnectIEs__value_PR;
typedef enum RUA_ConnectionlessTransferIEs__value_PR {
	RUA_ConnectionlessTransferIEs__value_PR_NOTHING,	/* No components present */
	RUA_ConnectionlessTransferIEs__value_PR_RANAP_Message
} RUA_ConnectionlessTransferIEs__value_PR;
typedef enum RUA_ErrorIndicationIEs__value_PR {
	RUA_ErrorIndicationIEs__value_PR_NOTHING,	/* No components present */
	RUA_ErrorIndicationIEs__value_PR_Cause,
	RUA_ErrorIndicationIEs__value_PR_CriticalityDiagnostics
} RUA_ErrorIndicationIEs__value_PR;

/* RUA_ProtocolIE-Field */
typedef struct RUA_ConnectIEs {
	RUA_ProtocolIE_ID_t	 id;
	RUA_Criticality_t	 criticality;
	struct RUA_ConnectIEs__value {
		RUA_ConnectIEs__value_PR present;
		union RUA_ConnectIEs__RUA_value_u {
			RUA_CN_DomainIndicator_t	 CN_DomainIndicator;
			RUA_Context_ID_t	 Context_ID;
			RUA_IntraDomainNasNodeSelector_t	 IntraDomainNasNodeSelector;
			RUA_Establishment_Cause_t	 Establishment_Cause;
			RUA_RANAP_Message_t	 RANAP_Message;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ConnectIEs_t;
typedef struct RUA_DirectTransferIEs {
	RUA_ProtocolIE_ID_t	 id;
	RUA_Criticality_t	 criticality;
	struct RUA_DirectTransferIEs__value {
		RUA_DirectTransferIEs__value_PR present;
		union RUA_DirectTransferIEs__RUA_value_u {
			RUA_CN_DomainIndicator_t	 CN_DomainIndicator;
			RUA_Context_ID_t	 Context_ID;
			RUA_RANAP_Message_t	 RANAP_Message;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_DirectTransferIEs_t;
typedef struct RUA_DisconnectIEs {
	RUA_ProtocolIE_ID_t	 id;
	RUA_Criticality_t	 criticality;
	struct RUA_DisconnectIEs__value {
		RUA_DisconnectIEs__value_PR present;
		union RUA_DisconnectIEs__RUA_value_u {
			RUA_CN_DomainIndicator_t	 CN_DomainIndicator;
			RUA_Context_ID_t	 Context_ID;
			RUA_Cause_t	 Cause;
			RUA_RANAP_Message_t	 RANAP_Message;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_DisconnectIEs_t;
typedef struct RUA_ConnectionlessTransferIEs {
	RUA_ProtocolIE_ID_t	 id;
	RUA_Criticality_t	 criticality;
	struct RUA_ConnectionlessTransferIEs__value {
		RUA_ConnectionlessTransferIEs__value_PR present;
		union RUA_ConnectionlessTransferIEs__RUA_value_u {
			RUA_RANAP_Message_t	 RANAP_Message;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ConnectionlessTransferIEs_t;
typedef struct RUA_ErrorIndicationIEs {
	RUA_ProtocolIE_ID_t	 id;
	RUA_Criticality_t	 criticality;
	struct RUA_ErrorIndicationIEs__value {
		RUA_ErrorIndicationIEs__value_PR present;
		union RUA_ErrorIndicationIEs__RUA_value_u {
			RUA_Cause_t	 Cause;
			RUA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ErrorIndicationIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_ConnectIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_ConnectIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RUA_ConnectIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_RUA_DirectTransferIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_DirectTransferIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_RUA_DirectTransferIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_RUA_DisconnectIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_DisconnectIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_RUA_DisconnectIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_RUA_ConnectionlessTransferIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_ConnectionlessTransferIEs_specs_13;
extern asn_TYPE_member_t asn_MBR_RUA_ConnectionlessTransferIEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_RUA_ErrorIndicationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_ErrorIndicationIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_RUA_ErrorIndicationIEs_17[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_ProtocolIE_Field_H_ */
#include <asn_internal.h>
