/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-Containers"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RUA_ProtocolIE_Container_H_
#define	_RUA_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RUA_ConnectIEs;
struct RUA_DirectTransferIEs;
struct RUA_DisconnectIEs;
struct RUA_ConnectionlessTransferIEs;
struct RUA_ErrorIndicationIEs;

/* RUA_ProtocolIE-Container */
typedef struct RUA_ProtocolIE_Container_769P0 {
	A_SEQUENCE_OF(struct RUA_ConnectIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ProtocolIE_Container_769P0_t;
typedef struct RUA_ProtocolIE_Container_769P1 {
	A_SEQUENCE_OF(struct RUA_DirectTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ProtocolIE_Container_769P1_t;
typedef struct RUA_ProtocolIE_Container_769P2 {
	A_SEQUENCE_OF(struct RUA_DisconnectIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ProtocolIE_Container_769P2_t;
typedef struct RUA_ProtocolIE_Container_769P3 {
	A_SEQUENCE_OF(struct RUA_ConnectionlessTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ProtocolIE_Container_769P3_t;
typedef struct RUA_ProtocolIE_Container_769P4 {
	A_SEQUENCE_OF(struct RUA_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ProtocolIE_Container_769P4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P0;
extern asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P0_specs_1;
extern asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P0_1[1];
extern asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P1;
extern asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P1_specs_3;
extern asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P1_3[1];
extern asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P2;
extern asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P2_specs_5;
extern asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P2_5[1];
extern asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P3;
extern asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P3_specs_7;
extern asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P3_7[1];
extern asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_RUA_ProtocolIE_Container_769P4;
extern asn_SET_OF_specifics_t asn_SPC_RUA_ProtocolIE_Container_769P4_specs_9;
extern asn_TYPE_member_t asn_MBR_RUA_ProtocolIE_Container_769P4_9[1];
extern asn_per_constraints_t asn_PER_type_RUA_ProtocolIE_Container_769P4_constr_9;

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_ProtocolIE_Container_H_ */
#include <asn_internal.h>
