/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-PDU-Contents"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RUA_ErrorIndication_H_
#define	_RUA_ErrorIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rua/RUA_ProtocolIE-Container.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RUA_ProtocolExtensionContainer;

/* RUA_ErrorIndication */
typedef struct RUA_ErrorIndication {
	RUA_ProtocolIE_Container_769P4_t	 protocolIEs;
	struct RUA_ProtocolExtensionContainer	*protocolExtensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_ErrorIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_ErrorIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_RUA_ErrorIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_RUA_ErrorIndication_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_ErrorIndication_H_ */
#include <asn_internal.h>
