/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-IEs"
 * 	found in "../../asn1/rua/rua-14.0.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RUA_CriticalityDiagnostics_IE_List_H_
#define	_RUA_CriticalityDiagnostics_IE_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <osmocom/rua/RUA_Criticality.h>
#include <osmocom/rua/RUA_ProtocolIE-ID.h>
#include <osmocom/rua/RUA_TypeOfError.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RUA_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct RUA_CriticalityDiagnostics_IE_List__Member {
	RUA_Criticality_t	 iECriticality;
	RUA_ProtocolIE_ID_t	 iE_ID;
	RUA_TypeOfError_t	 typeOfError;
	struct RUA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CriticalityDiagnostics_IE_List__Member;

/* RUA_CriticalityDiagnostics-IE-List */
typedef struct RUA_CriticalityDiagnostics_IE_List {
	A_SEQUENCE_OF(CriticalityDiagnostics_IE_List__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_CriticalityDiagnostics_IE_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_CriticalityDiagnostics_IE_List;
extern asn_SET_OF_specifics_t asn_SPC_RUA_CriticalityDiagnostics_IE_List_specs_1;
extern asn_TYPE_member_t asn_MBR_RUA_CriticalityDiagnostics_IE_List_1[1];
extern asn_per_constraints_t asn_PER_type_RUA_CriticalityDiagnostics_IE_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_CriticalityDiagnostics_IE_List_H_ */
#include <asn_internal.h>
