/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_CGI.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
asn_TYPE_member_t asn_MBR_RANAP_CGI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_CGI, pLMNidentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_PLMNidentity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pLMNidentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_CGI, lAC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_LAC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lAC"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_CGI, cI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cI"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_CGI, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P137,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_CGI_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_RANAP_CGI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_CGI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMNidentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lAC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_CGI_specs_1 = {
	sizeof(struct RANAP_CGI),
	offsetof(struct RANAP_CGI, _asn_ctx),
	asn_MAP_RANAP_CGI_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RANAP_CGI_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_CGI = {
	"CGI",
	"CGI",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_CGI_tags_1,
	sizeof(asn_DEF_RANAP_CGI_tags_1)
		/sizeof(asn_DEF_RANAP_CGI_tags_1[0]), /* 1 */
	asn_DEF_RANAP_CGI_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_CGI_tags_1)
		/sizeof(asn_DEF_RANAP_CGI_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_CGI_1,
	4,	/* Elements count */
	&asn_SPC_RANAP_CGI_specs_1	/* Additional specs */
};

