/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_Cause.h>

static asn_oer_constraints_t asn_OER_type_RANAP_Cause_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RANAP_Cause_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RANAP_Cause_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.radioNetwork),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseRadioNetwork,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioNetwork"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.transmissionNetwork),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseTransmissionNetwork,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmissionNetwork"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.nAS),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseNAS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nAS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.protocol),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseProtocol,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocol"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.misc),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseMisc,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"misc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.non_Standard),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseNon_Standard,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"non-Standard"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_Cause, choice.radioNetworkExtension),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_CauseRadioNetworkExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioNetworkExtension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_Cause_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioNetwork */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transmissionNetwork */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nAS */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* protocol */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* misc */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* non-Standard */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* radioNetworkExtension */
};
asn_CHOICE_specifics_t asn_SPC_RANAP_Cause_specs_1 = {
	sizeof(struct RANAP_Cause),
	offsetof(struct RANAP_Cause, _asn_ctx),
	offsetof(struct RANAP_Cause, present),
	sizeof(((struct RANAP_Cause *)0)->present),
	asn_MAP_RANAP_Cause_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_Cause = {
	"Cause",
	"Cause",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RANAP_Cause_constr_1, &asn_PER_type_RANAP_Cause_constr_1, CHOICE_constraint },
	asn_MBR_RANAP_Cause_1,
	7,	/* Elements count */
	&asn_SPC_RANAP_Cause_specs_1	/* Additional specs */
};

