/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_UERegistrationQueryResult.h>

static asn_oer_constraints_t asn_OER_type_RANAP_UERegistrationQueryResult_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_RANAP_UERegistrationQueryResult_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RANAP_UERegistrationQueryResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_UERegistrationQueryResult, choice.uE_IsServed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_UE_IsServed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uE-IsServed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_UERegistrationQueryResult, choice.uE_IsNotServed),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_UE_IsNotServed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uE-IsNotServed"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_UERegistrationQueryResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uE-IsServed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* uE-IsNotServed */
};
static asn_CHOICE_specifics_t asn_SPC_RANAP_UERegistrationQueryResult_specs_1 = {
	sizeof(struct RANAP_UERegistrationQueryResult),
	offsetof(struct RANAP_UERegistrationQueryResult, _asn_ctx),
	offsetof(struct RANAP_UERegistrationQueryResult, present),
	sizeof(((struct RANAP_UERegistrationQueryResult *)0)->present),
	asn_MAP_RANAP_UERegistrationQueryResult_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_UERegistrationQueryResult = {
	"UERegistrationQueryResult",
	"UERegistrationQueryResult",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RANAP_UERegistrationQueryResult_constr_1, &asn_PER_type_RANAP_UERegistrationQueryResult_constr_1, CHOICE_constraint },
	asn_MBR_RANAP_UERegistrationQueryResult_1,
	2,	/* Elements count */
	&asn_SPC_RANAP_UERegistrationQueryResult_specs_1	/* Additional specs */
};

