/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Descriptions"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_RANAP-PDU.h>

static asn_oer_constraints_t asn_OER_type_RANAP_RANAP_PDU_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_RANAP_RANAP_PDU_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RANAP_RANAP_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_RANAP_PDU, choice.initiatingMessage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_InitiatingMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiatingMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_RANAP_PDU, choice.successfulOutcome),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_SuccessfulOutcome,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"successfulOutcome"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_RANAP_PDU, choice.unsuccessfulOutcome),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_UnsuccessfulOutcome,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unsuccessfulOutcome"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_RANAP_PDU, choice.outcome),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_Outcome,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outcome"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_RANAP_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initiatingMessage */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* successfulOutcome */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* unsuccessfulOutcome */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* outcome */
};
static asn_CHOICE_specifics_t asn_SPC_RANAP_RANAP_PDU_specs_1 = {
	sizeof(struct RANAP_RANAP_PDU),
	offsetof(struct RANAP_RANAP_PDU, _asn_ctx),
	offsetof(struct RANAP_RANAP_PDU, present),
	sizeof(((struct RANAP_RANAP_PDU *)0)->present),
	asn_MAP_RANAP_RANAP_PDU_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_RANAP_PDU = {
	"RANAP-PDU",
	"RANAP-PDU",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RANAP_RANAP_PDU_constr_1, &asn_PER_type_RANAP_RANAP_PDU_constr_1, CHOICE_constraint },
	asn_MBR_RANAP_RANAP_PDU_1,
	4,	/* Elements count */
	&asn_SPC_RANAP_RANAP_PDU_specs_1	/* Additional specs */
};

