/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_SGSN-Group-Identity.h>

static asn_oer_constraints_t asn_OER_type_RANAP_SGSN_Group_Identity_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_RANAP_SGSN_Group_Identity_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RANAP_SGSN_Group_Identity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_SGSN_Group_Identity, choice.null_NRI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_Null_NRI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"null-NRI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_SGSN_Group_Identity, choice.sGSN_Group_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_SGSN_Group_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sGSN-Group-ID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_SGSN_Group_Identity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* null-NRI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sGSN-Group-ID */
};
static asn_CHOICE_specifics_t asn_SPC_RANAP_SGSN_Group_Identity_specs_1 = {
	sizeof(struct RANAP_SGSN_Group_Identity),
	offsetof(struct RANAP_SGSN_Group_Identity, _asn_ctx),
	offsetof(struct RANAP_SGSN_Group_Identity, present),
	sizeof(((struct RANAP_SGSN_Group_Identity *)0)->present),
	asn_MAP_RANAP_SGSN_Group_Identity_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_SGSN_Group_Identity = {
	"SGSN-Group-Identity",
	"SGSN-Group-Identity",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RANAP_SGSN_Group_Identity_constr_1, &asn_PER_type_RANAP_SGSN_Group_Identity_constr_1, CHOICE_constraint },
	asn_MBR_RANAP_SGSN_Group_Identity_1,
	2,	/* Elements count */
	&asn_SPC_RANAP_SGSN_Group_Identity_specs_1	/* Additional specs */
};

