/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_GA-Point.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
asn_TYPE_member_t asn_MBR_RANAP_GA_Point_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_GA_Point, geographicalCoordinates),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_GeographicalCoordinates,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"geographicalCoordinates"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_GA_Point, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P142,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_GA_Point_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_RANAP_GA_Point_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_GA_Point_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* geographicalCoordinates */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_GA_Point_specs_1 = {
	sizeof(struct RANAP_GA_Point),
	offsetof(struct RANAP_GA_Point, _asn_ctx),
	asn_MAP_RANAP_GA_Point_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_RANAP_GA_Point_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_GA_Point = {
	"GA-Point",
	"GA-Point",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_GA_Point_tags_1,
	sizeof(asn_DEF_RANAP_GA_Point_tags_1)
		/sizeof(asn_DEF_RANAP_GA_Point_tags_1[0]), /* 1 */
	asn_DEF_RANAP_GA_Point_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_GA_Point_tags_1)
		/sizeof(asn_DEF_RANAP_GA_Point_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_GA_Point_1,
	2,	/* Elements count */
	&asn_SPC_RANAP_GA_Point_specs_1	/* Additional specs */
};

