/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_SDU-ErrorRatio.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
static int
memb_RANAP_mantissa_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_RANAP_exponent_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_RANAP_mantissa_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (1..9) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RANAP_mantissa_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (1..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RANAP_exponent_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (1..6) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RANAP_exponent_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  6 }	/* (1..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RANAP_SDU_ErrorRatio_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_SDU_ErrorRatio, mantissa),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_RANAP_mantissa_constr_2, &asn_PER_memb_RANAP_mantissa_constr_2,  memb_RANAP_mantissa_constraint_1 },
		0, 0, /* No default value */
		"mantissa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_SDU_ErrorRatio, exponent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_RANAP_exponent_constr_3, &asn_PER_memb_RANAP_exponent_constr_3,  memb_RANAP_exponent_constraint_1 },
		0, 0, /* No default value */
		"exponent"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_SDU_ErrorRatio, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P187,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_SDU_ErrorRatio_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_RANAP_SDU_ErrorRatio_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_SDU_ErrorRatio_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mantissa */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* exponent */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_SDU_ErrorRatio_specs_1 = {
	sizeof(struct RANAP_SDU_ErrorRatio),
	offsetof(struct RANAP_SDU_ErrorRatio, _asn_ctx),
	asn_MAP_RANAP_SDU_ErrorRatio_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RANAP_SDU_ErrorRatio_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_SDU_ErrorRatio = {
	"SDU-ErrorRatio",
	"SDU-ErrorRatio",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_SDU_ErrorRatio_tags_1,
	sizeof(asn_DEF_RANAP_SDU_ErrorRatio_tags_1)
		/sizeof(asn_DEF_RANAP_SDU_ErrorRatio_tags_1[0]), /* 1 */
	asn_DEF_RANAP_SDU_ErrorRatio_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_SDU_ErrorRatio_tags_1)
		/sizeof(asn_DEF_RANAP_SDU_ErrorRatio_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_SDU_ErrorRatio_1,
	3,	/* Elements count */
	&asn_SPC_RANAP_SDU_ErrorRatio_specs_1	/* Additional specs */
};

