/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_IuSigConId-IE-ContainerList.h>

int
RANAP_IuSigConId_IE_ContainerList_1097P0_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 250)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using RANAP_ProtocolIE_ContainerList_7782P12,
 * so here we adjust the DEF accordingly.
 */
int
RANAP_IuSigConId_IE_ContainerList_1097P1_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 250)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using RANAP_ProtocolIE_ContainerList_7782P13,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_RANAP_IuSigConId_IE_ContainerList_1097P0_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..250)) */};
asn_per_constraints_t asn_PER_type_RANAP_IuSigConId_IE_ContainerList_1097P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  250 }	/* (SIZE(1..250)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RANAP_IuSigConId_IE_ContainerList_1097P1_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..250)) */};
asn_per_constraints_t asn_PER_type_RANAP_IuSigConId_IE_ContainerList_1097P1_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  250 }	/* (SIZE(1..250)) */,
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0 = {
	"IuSigConId-IE-ContainerList",
	"IuSigConId-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1,
	sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1)
		/sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1[0]), /* 1 */
	asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1)
		/sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P0_tags_1[0]), /* 1 */
	{ &asn_OER_type_RANAP_IuSigConId_IE_ContainerList_1097P0_constr_1, &asn_PER_type_RANAP_IuSigConId_IE_ContainerList_1097P0_constr_1, RANAP_IuSigConId_IE_ContainerList_1097P0_constraint },
	asn_MBR_RANAP_ProtocolIE_ContainerList_7782P12_25,
	1,	/* Single element */
	&asn_SPC_RANAP_ProtocolIE_ContainerList_7782P12_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1 = {
	"IuSigConId-IE-ContainerList",
	"IuSigConId-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2,
	sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2)
		/sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2[0]), /* 1 */
	asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2)
		/sizeof(asn_DEF_RANAP_IuSigConId_IE_ContainerList_1097P1_tags_2[0]), /* 1 */
	{ &asn_OER_type_RANAP_IuSigConId_IE_ContainerList_1097P1_constr_2, &asn_PER_type_RANAP_IuSigConId_IE_ContainerList_1097P1_constr_2, RANAP_IuSigConId_IE_ContainerList_1097P1_constraint },
	asn_MBR_RANAP_ProtocolIE_ContainerList_7782P13_27,
	1,	/* Single element */
	&asn_SPC_RANAP_ProtocolIE_ContainerList_7782P13_specs_27	/* Additional specs */
};

