/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_MBMSIPMulticastAddressandAPNlist.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
asn_TYPE_member_t asn_MBR_RANAP_MBMSIPMulticastAddressandAPNlist_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_MBMSIPMulticastAddressandAPNlist, tMGI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_TMGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tMGI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_MBMSIPMulticastAddressandAPNlist, iPMulticastAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_IPMulticastAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iPMulticastAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_MBMSIPMulticastAddressandAPNlist, aPN),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_APN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aPN"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_MBMSIPMulticastAddressandAPNlist, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P178,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_MBMSIPMulticastAddressandAPNlist_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_MBMSIPMulticastAddressandAPNlist_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tMGI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iPMulticastAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aPN */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_MBMSIPMulticastAddressandAPNlist_specs_1 = {
	sizeof(struct RANAP_MBMSIPMulticastAddressandAPNlist),
	offsetof(struct RANAP_MBMSIPMulticastAddressandAPNlist, _asn_ctx),
	asn_MAP_RANAP_MBMSIPMulticastAddressandAPNlist_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RANAP_MBMSIPMulticastAddressandAPNlist_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist = {
	"MBMSIPMulticastAddressandAPNlist",
	"MBMSIPMulticastAddressandAPNlist",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1,
	sizeof(asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1)
		/sizeof(asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1[0]), /* 1 */
	asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1)
		/sizeof(asn_DEF_RANAP_MBMSIPMulticastAddressandAPNlist_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_MBMSIPMulticastAddressandAPNlist_1,
	4,	/* Elements count */
	&asn_SPC_RANAP_MBMSIPMulticastAddressandAPNlist_specs_1	/* Additional specs */
};

