/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_Additional-CSPS-coordination-information.h>

#include <osmocom/ranap/RANAP_LAI.h>
#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
static int
memb_RANAP_nRI_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_RANAP_nRI_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	10	/* (SIZE(10..10)) */};
static asn_per_constraints_t asn_PER_memb_RANAP_nRI_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  10,  10 }	/* (SIZE(10..10)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RANAP_Additional_CSPS_coordination_information_1[] = {
	{ ATF_POINTER, 5, offsetof(struct RANAP_Additional_CSPS_coordination_information, old_LAI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_LAI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"old-LAI"
		},
	{ ATF_POINTER, 4, offsetof(struct RANAP_Additional_CSPS_coordination_information, old_RAC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_RAC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"old-RAC"
		},
	{ ATF_POINTER, 3, offsetof(struct RANAP_Additional_CSPS_coordination_information, nRI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_RANAP_nRI_constr_4, &asn_PER_memb_RANAP_nRI_constr_4,  memb_RANAP_nRI_constraint_1 },
		0, 0, /* No default value */
		"nRI"
		},
	{ ATF_POINTER, 2, offsetof(struct RANAP_Additional_CSPS_coordination_information, uE_is_Attaching),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uE-is-Attaching"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_Additional_CSPS_coordination_information, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P124,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_Additional_CSPS_coordination_information_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_Additional_CSPS_coordination_information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* old-LAI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* old-RAC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nRI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uE-is-Attaching */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_RANAP_Additional_CSPS_coordination_information_specs_1 = {
	sizeof(struct RANAP_Additional_CSPS_coordination_information),
	offsetof(struct RANAP_Additional_CSPS_coordination_information, _asn_ctx),
	asn_MAP_RANAP_Additional_CSPS_coordination_information_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RANAP_Additional_CSPS_coordination_information_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_Additional_CSPS_coordination_information = {
	"Additional-CSPS-coordination-information",
	"Additional-CSPS-coordination-information",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1,
	sizeof(asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1)
		/sizeof(asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1[0]), /* 1 */
	asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1)
		/sizeof(asn_DEF_RANAP_Additional_CSPS_coordination_information_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_Additional_CSPS_coordination_information_1,
	5,	/* Elements count */
	&asn_SPC_RANAP_Additional_CSPS_coordination_information_specs_1	/* Additional specs */
};

