/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_MDT-Report-Parameters.h>

asn_TYPE_member_t asn_MBR_RANAP_MDT_Report_Parameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_MDT_Report_Parameters, reportInterval),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ReportInterval,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_MDT_Report_Parameters, reportAmount),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ReportAmount,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportAmount"
		},
};
static const ber_tlv_tag_t asn_DEF_RANAP_MDT_Report_Parameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_MDT_Report_Parameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportInterval */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reportAmount */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_MDT_Report_Parameters_specs_1 = {
	sizeof(struct RANAP_MDT_Report_Parameters),
	offsetof(struct RANAP_MDT_Report_Parameters, _asn_ctx),
	asn_MAP_RANAP_MDT_Report_Parameters_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_MDT_Report_Parameters = {
	"MDT-Report-Parameters",
	"MDT-Report-Parameters",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_MDT_Report_Parameters_tags_1,
	sizeof(asn_DEF_RANAP_MDT_Report_Parameters_tags_1)
		/sizeof(asn_DEF_RANAP_MDT_Report_Parameters_tags_1[0]), /* 1 */
	asn_DEF_RANAP_MDT_Report_Parameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_MDT_Report_Parameters_tags_1)
		/sizeof(asn_DEF_RANAP_MDT_Report_Parameters_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_MDT_Report_Parameters_1,
	2,	/* Elements count */
	&asn_SPC_RANAP_MDT_Report_Parameters_specs_1	/* Additional specs */
};

