/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_ReportInterval.h>

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_RANAP_ReportInterval_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RANAP_ReportInterval_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  12 }	/* (0..12,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_RANAP_ReportInterval_value2enum_1[] = {
	{ 0,	5,	"ms250" },
	{ 1,	5,	"ms500" },
	{ 2,	6,	"ms1000" },
	{ 3,	6,	"ms2000" },
	{ 4,	6,	"ms3000" },
	{ 5,	6,	"ms4000" },
	{ 6,	6,	"ms6000" },
	{ 7,	7,	"ms12000" },
	{ 8,	7,	"ms16000" },
	{ 9,	7,	"ms20000" },
	{ 10,	7,	"ms24000" },
	{ 11,	7,	"ms32000" },
	{ 12,	7,	"ms64000" },
	{ 13,	6,	"ms8000" },
	{ 14,	7,	"ms28000" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_RANAP_ReportInterval_enum2value_1[] = {
	2,	/* ms1000(2) */
	7,	/* ms12000(7) */
	8,	/* ms16000(8) */
	3,	/* ms2000(3) */
	9,	/* ms20000(9) */
	10,	/* ms24000(10) */
	0,	/* ms250(0) */
	14,	/* ms28000(14) */
	4,	/* ms3000(4) */
	11,	/* ms32000(11) */
	5,	/* ms4000(5) */
	1,	/* ms500(1) */
	6,	/* ms6000(6) */
	12,	/* ms64000(12) */
	13	/* ms8000(13) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_RANAP_ReportInterval_specs_1 = {
	asn_MAP_RANAP_ReportInterval_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RANAP_ReportInterval_enum2value_1,	/* N => "tag"; sorted by N */
	15,	/* Number of elements in the maps */
	14,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_RANAP_ReportInterval_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RANAP_ReportInterval = {
	"ReportInterval",
	"ReportInterval",
	&asn_OP_NativeEnumerated,
	asn_DEF_RANAP_ReportInterval_tags_1,
	sizeof(asn_DEF_RANAP_ReportInterval_tags_1)
		/sizeof(asn_DEF_RANAP_ReportInterval_tags_1[0]), /* 1 */
	asn_DEF_RANAP_ReportInterval_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_ReportInterval_tags_1)
		/sizeof(asn_DEF_RANAP_ReportInterval_tags_1[0]), /* 1 */
	{ &asn_OER_type_RANAP_ReportInterval_constr_1, &asn_PER_type_RANAP_ReportInterval_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RANAP_ReportInterval_specs_1	/* Additional specs */
};

