/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_GA-AltitudeAndDirection.h>

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_RANAP_altitude_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 32767)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_RANAP_directionOfAltitude_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_RANAP_directionOfAltitude_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_RANAP_altitude_constr_5 CC_NOTUSED = {
	{ 2, 1 }	/* (0..32767) */,
	-1};
static asn_per_constraints_t asn_PER_memb_RANAP_altitude_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 15,  15,  0,  32767 }	/* (0..32767) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_RANAP_directionOfAltitude_value2enum_2[] = {
	{ 0,	6,	"height" },
	{ 1,	5,	"depth" }
};
static const unsigned int asn_MAP_RANAP_directionOfAltitude_enum2value_2[] = {
	1,	/* depth(1) */
	0	/* height(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_RANAP_directionOfAltitude_specs_2 = {
	asn_MAP_RANAP_directionOfAltitude_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_RANAP_directionOfAltitude_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_RANAP_directionOfAltitude_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_RANAP_directionOfAltitude_2 = {
	"directionOfAltitude",
	"directionOfAltitude",
	&asn_OP_NativeEnumerated,
	asn_DEF_RANAP_directionOfAltitude_tags_2,
	sizeof(asn_DEF_RANAP_directionOfAltitude_tags_2)
		/sizeof(asn_DEF_RANAP_directionOfAltitude_tags_2[0]) - 1, /* 1 */
	asn_DEF_RANAP_directionOfAltitude_tags_2,	/* Same as above */
	sizeof(asn_DEF_RANAP_directionOfAltitude_tags_2)
		/sizeof(asn_DEF_RANAP_directionOfAltitude_tags_2[0]), /* 2 */
	{ &asn_OER_type_RANAP_directionOfAltitude_constr_2, &asn_PER_type_RANAP_directionOfAltitude_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RANAP_directionOfAltitude_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANAP_GA_AltitudeAndDirection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_GA_AltitudeAndDirection, directionOfAltitude),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_directionOfAltitude_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"directionOfAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_GA_AltitudeAndDirection, altitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_RANAP_altitude_constr_5, &asn_PER_memb_RANAP_altitude_constr_5,  memb_RANAP_altitude_constraint_1 },
		0, 0, /* No default value */
		"altitude"
		},
};
static const ber_tlv_tag_t asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_GA_AltitudeAndDirection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* directionOfAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* altitude */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_GA_AltitudeAndDirection_specs_1 = {
	sizeof(struct RANAP_GA_AltitudeAndDirection),
	offsetof(struct RANAP_GA_AltitudeAndDirection, _asn_ctx),
	asn_MAP_RANAP_GA_AltitudeAndDirection_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_GA_AltitudeAndDirection = {
	"GA-AltitudeAndDirection",
	"GA-AltitudeAndDirection",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1,
	sizeof(asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1)
		/sizeof(asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1[0]), /* 1 */
	asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1)
		/sizeof(asn_DEF_RANAP_GA_AltitudeAndDirection_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_GA_AltitudeAndDirection_1,
	2,	/* Elements count */
	&asn_SPC_RANAP_GA_AltitudeAndDirection_specs_1	/* Additional specs */
};

