/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_Requested-RAB-Parameter-Values.h>

#include <osmocom/ranap/RANAP_Requested-RAB-Parameter-MaxBitrateList.h>
#include <osmocom/ranap/RANAP_Requested-RAB-Parameter-GuaranteedBitrateList.h>
#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
asn_TYPE_member_t asn_MBR_RANAP_Requested_RAB_Parameter_Values_1[] = {
	{ ATF_POINTER, 3, offsetof(struct RANAP_Requested_RAB_Parameter_Values, requestedMaxBitrates),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_Requested_RAB_Parameter_MaxBitrateList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestedMaxBitrates"
		},
	{ ATF_POINTER, 2, offsetof(struct RANAP_Requested_RAB_Parameter_Values, requestedGuaranteedBitrates),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_Requested_RAB_Parameter_GuaranteedBitrateList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestedGuaranteedBitrates"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_Requested_RAB_Parameter_Values, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P179,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_Requested_RAB_Parameter_Values_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_Requested_RAB_Parameter_Values_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requestedMaxBitrates */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* requestedGuaranteedBitrates */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_Requested_RAB_Parameter_Values_specs_1 = {
	sizeof(struct RANAP_Requested_RAB_Parameter_Values),
	offsetof(struct RANAP_Requested_RAB_Parameter_Values, _asn_ctx),
	asn_MAP_RANAP_Requested_RAB_Parameter_Values_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RANAP_Requested_RAB_Parameter_Values_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_Requested_RAB_Parameter_Values = {
	"Requested-RAB-Parameter-Values",
	"Requested-RAB-Parameter-Values",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1,
	sizeof(asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1)
		/sizeof(asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1[0]), /* 1 */
	asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1)
		/sizeof(asn_DEF_RANAP_Requested_RAB_Parameter_Values_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_Requested_RAB_Parameter_Values_1,
	3,	/* Elements count */
	&asn_SPC_RANAP_Requested_RAB_Parameter_Values_specs_1	/* Additional specs */
};

