/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_TrCH-ID.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
asn_TYPE_member_t asn_MBR_RANAP_TrCH_ID_1[] = {
	{ ATF_POINTER, 4, offsetof(struct RANAP_TrCH_ID, dCH_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_DCH_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dCH-ID"
		},
	{ ATF_POINTER, 3, offsetof(struct RANAP_TrCH_ID, dSCH_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_DSCH_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dSCH-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct RANAP_TrCH_ID, uSCH_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_USCH_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uSCH-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_TrCH_ID, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P207,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_TrCH_ID_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_RANAP_TrCH_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_TrCH_ID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dCH-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dSCH-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uSCH-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RANAP_TrCH_ID_specs_1 = {
	sizeof(struct RANAP_TrCH_ID),
	offsetof(struct RANAP_TrCH_ID, _asn_ctx),
	asn_MAP_RANAP_TrCH_ID_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RANAP_TrCH_ID_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_TrCH_ID = {
	"TrCH-ID",
	"TrCH-ID",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_TrCH_ID_tags_1,
	sizeof(asn_DEF_RANAP_TrCH_ID_tags_1)
		/sizeof(asn_DEF_RANAP_TrCH_ID_tags_1[0]), /* 1 */
	asn_DEF_RANAP_TrCH_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_TrCH_ID_tags_1)
		/sizeof(asn_DEF_RANAP_TrCH_ID_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_TrCH_ID_1,
	4,	/* Elements count */
	&asn_SPC_RANAP_TrCH_ID_specs_1	/* Additional specs */
};

