/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_IntegrityProtectionInformation.h>

#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
static asn_TYPE_member_t asn_MBR_RANAP_IntegrityProtectionInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_IntegrityProtectionInformation, permittedAlgorithms),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_PermittedIntegrityProtectionAlgorithms,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"permittedAlgorithms"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANAP_IntegrityProtectionInformation, key),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_IntegrityProtectionKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"key"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_IntegrityProtectionInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P152,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_IntegrityProtectionInformation_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_RANAP_IntegrityProtectionInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_IntegrityProtectionInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* permittedAlgorithms */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* key */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_RANAP_IntegrityProtectionInformation_specs_1 = {
	sizeof(struct RANAP_IntegrityProtectionInformation),
	offsetof(struct RANAP_IntegrityProtectionInformation, _asn_ctx),
	asn_MAP_RANAP_IntegrityProtectionInformation_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RANAP_IntegrityProtectionInformation_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_IntegrityProtectionInformation = {
	"IntegrityProtectionInformation",
	"IntegrityProtectionInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_IntegrityProtectionInformation_tags_1,
	sizeof(asn_DEF_RANAP_IntegrityProtectionInformation_tags_1)
		/sizeof(asn_DEF_RANAP_IntegrityProtectionInformation_tags_1[0]), /* 1 */
	asn_DEF_RANAP_IntegrityProtectionInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_IntegrityProtectionInformation_tags_1)
		/sizeof(asn_DEF_RANAP_IntegrityProtectionInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_IntegrityProtectionInformation_1,
	3,	/* Elements count */
	&asn_SPC_RANAP_IntegrityProtectionInformation_specs_1	/* Additional specs */
};

