/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "../../asn1/ranap/ranap-14.1.0.asn1"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -no-gen-example`
 */

#include <osmocom/ranap/RANAP_RAB-SetupOrModifyItemSecond.h>

#include <osmocom/ranap/RANAP_PDP-TypeInformation.h>
#include <osmocom/ranap/RANAP_ProtocolExtensionContainer.h>
static asn_TYPE_member_t asn_MBR_RANAP_RAB_SetupOrModifyItemSecond_1[] = {
	{ ATF_POINTER, 7, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, pDP_TypeInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_PDP_TypeInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDP-TypeInformation"
		},
	{ ATF_POINTER, 6, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, dataVolumeReportingIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_DataVolumeReportingIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataVolumeReportingIndication"
		},
	{ ATF_POINTER, 5, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, dl_GTP_PDU_SequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_DL_GTP_PDU_SequenceNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-GTP-PDU-SequenceNumber"
		},
	{ ATF_POINTER, 4, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, ul_GTP_PDU_SequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_UL_GTP_PDU_SequenceNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-GTP-PDU-SequenceNumber"
		},
	{ ATF_POINTER, 3, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, dl_N_PDU_SequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_DL_N_PDU_SequenceNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-N-PDU-SequenceNumber"
		},
	{ ATF_POINTER, 2, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, ul_N_PDU_SequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_UL_N_PDU_SequenceNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-N-PDU-SequenceNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ProtocolExtensionContainer_7796P65,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RANAP_RAB_SetupOrModifyItemSecond_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANAP_RAB_SetupOrModifyItemSecond_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pDP-TypeInformation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dataVolumeReportingIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dl-GTP-PDU-SequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ul-GTP-PDU-SequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dl-N-PDU-SequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ul-N-PDU-SequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_RANAP_RAB_SetupOrModifyItemSecond_specs_1 = {
	sizeof(struct RANAP_RAB_SetupOrModifyItemSecond),
	offsetof(struct RANAP_RAB_SetupOrModifyItemSecond, _asn_ctx),
	asn_MAP_RANAP_RAB_SetupOrModifyItemSecond_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_RANAP_RAB_SetupOrModifyItemSecond_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANAP_RAB_SetupOrModifyItemSecond = {
	"RAB-SetupOrModifyItemSecond",
	"RAB-SetupOrModifyItemSecond",
	&asn_OP_SEQUENCE,
	asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1,
	sizeof(asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1)
		/sizeof(asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1[0]), /* 1 */
	asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1)
		/sizeof(asn_DEF_RANAP_RAB_SetupOrModifyItemSecond_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANAP_RAB_SetupOrModifyItemSecond_1,
	7,	/* Elements count */
	&asn_SPC_RANAP_RAB_SetupOrModifyItemSecond_specs_1	/* Additional specs */
};

